AzureAD/microsoft-authentication-library-for-js

- README.md
- devApps/VanillaJSTestApp/index_LoginPopup.html
- devApps/VanillaJSTestApp/minimal.html
- msal.js is in preview
- explanations for IE11.
> Improving the Readme.md and devapps:

- README.md
(not mentioning registration to B2C as the example is not showing B2C)
> Adding a bullet point about app registration

- devApps/VanillaJSTestApp-b2c/index.html
Change log -> logMessage in `authCallback`.
> Fix typo in VanillaJSTestApp-b2c index.html

- src/UserAgentApplication.ts
> Remove default border from iframe

- src/UserAgentApplication.ts
- src/index.ts
Changes in Msal-core for msal-angular wrapper.
> changes for msalAngular WRapper

- src/UserAgentApplication.ts
Fixes #322
Let me know if I should add tests.
> Call ResolveEndpointsAsync on correct authority in acquireTokenSilent

- README.md
- contributing.md
- lib/msal-angular/README.md
- lib/msal-angularjs/README.md
- lib/msal-core/README.md
- Added contributing guide
- Added advanced topics in readmes
> Clean up of Readmes for msal core, angularjs and angular

- lib/msal-core/README.md
@nehaagrawal Can you please review these updates and merge the PR.
> Update Readme to include usage code

- lib/msal-core/samples/VanillaJSTestApp-b2c/Readme.md
Just change the Readme file extension so that the file is displayed with formatting on github
> Rename Readme.txt to Readme.md

- lib/msal-core/samples/VanillaJSTestApp/index_LoginRedirect.html
checkin the actual changes needed with a new PR to support call back functionality for acquireTokenRedirect()
> Revert the changes for redirect sample

- .editorconfig
- .gitattributes
Add .editorconfig and .gitattributes to normalize editing across IDEs.
> Adding support for .editorconfig and .gitattributes in MSAL JS

- lib/msal-core/samples/VanillaJSTestApp/Readme.md
- lib/msal-core/samples/VanillaJSTestApp/package.json
- lib/msal-core/samples/VanillaJSTestApp/server.js
* add start script to make it easier to use common start in node
* update documentation
* fix listening log in server to wait until server has started
> Add start script for node server in test app and small cleanup

- lib/msal-core/src/UserAgentApplication.ts
- lib/msal-core/src/Utils.ts
This PR covers the preliminary work for refactoring the MSAL.js library. The bulk of this work consists of reorganizing functions within the file to be more logically organized around functionality, as well as more comprehensive comments and TODO action items added throughout the file. 
**This PR includes only code reshuffle and no other refactoring**
- Future PRs will complete these TODO action items and build upon the reorganizing done here, possibly splitting UserAgentApplication into multiple files.
- Our strategy is to structure the PRs for better test isolation and introduce functionality in incremental PRs. 
- The TODOs are carried over from the work done in Config and Error, the code will contain TODOs until we mark the last PR down in this sequence.
> API Changes Step 0: Organization and Comments

- lib/msal-angular/package.json
- lib/msal-core/package.json
update typedoc to fix travis build
> update typedoc version

- lib/msal-core/src/UserAgentApplication.ts
- lib/msal-core/src/error/AuthError.ts
- lib/msal-core/src/error/ClientAuthError.ts
- lib/msal-core/src/error/ClientConfigurationError.ts
- lib/msal-core/src/error/InteractionRequiredAuthError.ts
- lib/msal-core/src/error/ServerError.ts
- lib/msal-core/tests/MSAL.spec.ts
- lib/msal-core/tests/error/error.spec.ts
Please review PR #586 before reviewing this.
This set of changes includes:
- Fixed stack variable and added tests to ensure stack trace was working
- Made errorMessage optional
> API Error Changes: Updates to Error Object

- lib/msal-core/LICENSE
- lib/msal-core/src/AadAuthority.ts
- lib/msal-core/src/AccessTokenCacheItem.ts
- lib/msal-core/src/AccessTokenKey.ts
- lib/msal-core/src/AccessTokenValue.ts
- lib/msal-core/src/AuthenticationRequestParameters.ts
- lib/msal-core/src/Authority.ts
- lib/msal-core/src/AuthorityFactory.ts
- lib/msal-core/src/B2cAuthority.ts
- lib/msal-core/src/ClientInfo.ts
- lib/msal-core/src/Constants.ts
- lib/msal-core/src/ErrorMessage.ts
- lib/msal-core/src/IInstanceDiscoveryResponse.ts
- lib/msal-core/src/ITenantDiscoveryResponse.ts
- lib/msal-core/src/IUri.ts
- lib/msal-core/src/IdToken.ts
- lib/msal-core/src/Logger.ts
- lib/msal-core/src/RequestInfo.ts
- lib/msal-core/src/Storage.ts
- lib/msal-core/src/Telemetry.ts
- lib/msal-core/src/User.ts
- lib/msal-core/src/UserAgentApplication.ts
- lib/msal-core/src/Utils.ts
- lib/msal-core/src/XHRClient.ts
Reduce license commenting to what is required
> reduce license comments

- lib/msal-core/package.json
Unsure why this was pinned in the first place but unpinning.  This Resolves #613
> Unpin tslib

- lib/msal-core/karma.conf.js
- lib/msal-core/package-lock.json
- lib/msal-core/package.json
- lib/msal-core/samples/VanillaJSTestApp/index.html
- lib/msal-core/samples/VanillaJSTestApp/index_LoginPopup.html
- lib/msal-core/src/Configuration.ts
- lib/msal-core/src/UserAgentApplication.ts
- lib/msal-core/src/index.ts
- lib/msal-core/tests/MSAL.spec.ts
- lib/msal-core/tests/mochaTests/Configuration.spec.ts
- lib/msal-core/tests/mochaTests/genericTests.ts
Moving build config from a public to a private function to clean up the user experience and make configuring an app easier.
Still to be done before merging
[x] write more tests
> abstract build configuration to clean up api

- lib/msal-core/src/Utils.ts
Makes ssoParam in addSSOParameter optional
> Minor SSOParams fix

- lib/msal-core/src/UserAgentApplication.ts
Remove all the config.state references
> References for config.state removed across

- README.md
- lib/msal-core/README.md
update code patterns in readme, will be followed by improved content, probably splitting apart confusing parts of the code.
> update readme code patterns

- lib/msal-core/src/AuthenticationParameters.ts
> AuthParams for link to types

- README.md
- lib/msal-core/README.md
Previously did not update base README, only msal-core README. This PR updates both to be accurate to latest dev code.
> Updating base README

- lib/msal-core/samples/VanillaJSTestApp/index.html
Updates vanilla sample with new version of library
> Update Vanilla Sample

- lib/msal-core/samples/UnifiedCacheTestApp/ADAL_OLD.html
- lib/msal-core/samples/UnifiedCacheTestApp/MSAL_OLD.html
- lib/msal-core/samples/UnifiedCacheTestApp/adal/adal.js
- lib/msal-core/samples/UnifiedCacheTestApp/index.html
- lib/msal-core/samples/UnifiedCacheTestApp/server.js
- lib/msal-core/samples/UnifiedCacheTestApp/tempMSAL_OLD.html
Working sample for UnifiedCache. Very rudimentary - will polish this when samples are closed.
> Unifiedcache adaltomsal

- lib/msal-core/package-lock.json
- lib/msal-core/package.json
- lib/msal-core/src/Utils.ts
- lib/msal-core/test/Utils.spec.ts
Will add more tests later in e2e or UT
> Migrating to base64.js instead of window.atob for base64 encode/decode

- lib/msal-core/src/UserAgentApplication.ts
While adding login_hint in addHintParameters, need to check if sid is already populated. Adding the check.
> add a missed sid check when adding login_hint

- lib/msal-core/docs/modules/_error_clientconfigurationerror_.html
- lib/msal-core/src/error/ClientConfigurationError.ts
No login callback exceptions are providing a broken link, this PR fixes the links
> fixed broken link to documentation basics in error message

- lib/msal-core/changelog.md
- lib/msal-core/package-lock.json
- lib/msal-core/package.json
- lib/msal-core/src/Constants.ts
> Publishing msal v1.0.2

- lib/msal-angular/changelog.md
Adding notes about `0.1.3` release and deprecation.
> Update msal-angular changelog with notes on 0.1.3

- lib/msal-core/src/UserAgentApplication.ts
- lib/msal-core/src/error/ClientConfigurationError.ts
- lib/msal-core/test/UserAgentApplication.spec.ts
add checks for empty request and throw new error
> Error check request

- lib/msal-core/package-lock.json
- lib/msal-core/src/Configuration.ts
- lib/msal-core/src/UserAgentApplication.ts
- lib/msal-core/src/error/ClientConfigurationError.ts
- lib/msal-core/src/telemetry/TelemetryManager.ts
- lib/msal-core/src/telemetry/TelemetryTypes.ts
- lib/msal-core/test/Configuration.spec.ts
- lib/msal-core/test/TestConstants.ts
- lib/msal-core/test/UserAgentApplication.spec.ts
- lib/msal-core/test/error/ClientConfigurationError.spec.ts
add telemetry config and construct telem manager
This will be the instance used to instrument code
> add telemetry config and construct telem manager

- lib/msal-core/src/Configuration.ts
- lib/msal-core/src/Constants.ts
This reverts commit 9e0dfe824f056da53989aabd93cb4f538a0d52c2, reversing
changes made to 1b55af5017e8ce2869463fdd5f66762c3723afa1.
> Revert "Merge pull request #851 from jodonnell/dev"

- README.md
Updated readme with  forceRefresh for MSAL 1.1.0
> Updated Readme.md with forceRefresh

- lib/msal-core/samples/VanillaJSTestApp/index_externalAPI.html
Fixes #821. Though we plan to follow up with a revamp of samples in MSAL JS, would like to get this out of the way until then.
> fixing a typo in the existing sample for external API, #821

- lib/msal-core/.eslintrc.json
- lib/msal-core/package.json
- lib/msal-core/src/AadAuthority.ts
- lib/msal-core/src/AccessTokenCacheItem.ts
- lib/msal-core/src/AccessTokenKey.ts
- lib/msal-core/src/AccessTokenValue.ts
- lib/msal-core/src/Account.ts
- lib/msal-core/src/Authority.ts
- lib/msal-core/src/B2cAuthority.ts
- lib/msal-core/src/ClientInfo.ts
- lib/msal-core/src/Configuration.ts
- lib/msal-core/src/IInstanceDiscoveryResponse.ts
- lib/msal-core/src/ITenantDiscoveryResponse.ts
- lib/msal-core/src/IUri.ts
- lib/msal-core/src/IdToken.ts
- lib/msal-core/src/Logger.ts
- lib/msal-core/src/ScopeSet.ts
- lib/msal-core/src/ServerRequestParameters.ts
- lib/msal-core/src/Storage.ts
- lib/msal-core/src/UserAgentApplication.ts
- lib/msal-core/src/XHRClient.ts
- lib/msal-core/src/utils/Constants.ts
- lib/msal-core/src/utils/CryptoUtils.ts
- lib/msal-core/src/utils/ResponseUtils.ts
- lib/msal-core/src/utils/TimeUtils.ts
- lib/msal-core/src/utils/TokenUtils.ts
- lib/msal-core/src/utils/UrlUtils.ts
Enables indent and quotes rules for Typescript files in the msal-core `src` folder. Will expand to other folders soon.
> Turn on eslint rules for indents and spacing

- package-lock.json
update package lock to deep resolve a safe version of lodash in lerna
> fix lerna vulnerability

- lib/msal-angularjs/tests/sample/bundle.js
- lib/msal-core/.eslintrc.json
- lib/msal-core/package-lock.json
- lib/msal-core/src/AadAuthority.ts
- lib/msal-core/src/ServerRequestParameters.ts
- lib/msal-core/src/UserAgentApplication.ts
- lib/msal-core/src/utils/ResponseUtils.ts
- lib/msal-core/src/utils/UrlUtils.ts
Add prefer const rule and fix for vars never reassigned
> add prefer const rule

- README.md
- lib/msal-core/README.md
> Update Readme to include "import" in usage

- lib/msal-core/.gitignore
- lib/msal-core/.npmignore
- lib/msal-core/.nycrc
- lib/msal-core/package-lock.json
- lib/msal-core/package.json
This PR adds code coverage to the build and test reports. Eventually this will be integrated into the pipeline reporting also.
> Adding code coverage

- lib/msal-core/samples/VanillaJSTestApp/index.html
- lib/msal-core/samples/VanillaJSTestApp/index_LoginPopup.html
- lib/msal-core/samples/VanillaJSTestApp/index_LoginRedirect.html
- lib/msal-core/samples/VanillaJSTestApp/index_externalAPI.html
- lib/msal-core/samples/VanillaJSTestApp/index_renewIdToken.html
- lib/msal-core/samples/VanillaJSTestApp/index_single_sign_on.html
Currently our samples have storeAuthStateInCookie set to true, which is forcing us to use cookies. We would like to prevent this behavior, so this PR will set these values to false.
> Remove cookie usage from samples

- lib/msal-core/README.md
Removed Roadmap from heading as we alkready have a roadmap on wiki.
> Updated Roadmap heading

- lib/msal-core/package.json
- lib/msal-core/src/utils/Constants.ts
Changes to version as we published `msal-1.2.0-beta.1`
> Changes to version as we published `msal-1.2.0-beta.1`

- lib/msal-core/src/cache/AuthCache.ts
- lib/msal-core/src/error/ClientAuthError.ts
- lib/msal-core/src/utils/Constants.ts
> Add "scopes" to check access token keys

- README.md
Added content to inform the user about finding the installation instructions in Readme.md for each lib.
> Updated Wiki with info about installing the libs

- lib/msal-core/README.md
The example and text below it was duplicated in this section
> Remove duplicate readme.md section

- lib/msal-core/src/error/ClientConfigurationError.ts
This PR is a duplicate of #942. It was created because there were issues with our CI builds merging from a forked repository.
> Fix Error Message for Redirect Callbacks in ClientConfigurationErrorMessage

- lib/msal-browser/src/interaction_handler/RedirectHandler.ts
- lib/msal-browser/src/network/FetchClient.ts
- lib/msal-browser/src/network/XhrClient.ts
- lib/msal-common/src/app/module/AuthorizationCodeModule.ts
- lib/msal-common/src/auth/ScopeSet.ts
- lib/msal-common/src/auth/authority/AadAuthority.ts
- lib/msal-common/src/auth/authority/Authority.ts
- lib/msal-common/src/cache/CacheHelpers.ts
- lib/msal-common/src/error/ClientAuthError.ts
- lib/msal-common/src/server/ServerAuthorizationCodeResponse.ts
- lib/msal-common/src/server/ServerCodeRequestParameters.ts
- lib/msal-common/src/server/ServerRequestParameters.ts
- lib/msal-common/src/server/ServerTokenRequestParameters.ts
- lib/msal-common/src/url/UrlString.ts
- lib/msal-common/src/utils/Constants.ts
- samples/VanillaJSTestApp/index_authCode.html
This PR adds code to perform the exchange of the authorization code for an access token.
This PR does not cover token caching or response validation, which will be part of a separate PR.
> Authorization Code Flow for Single Page Applications: Exchange Code for Token

- lib/msal-core/src/utils/WindowUtils.ts
To fix #1165, add "allow-forms" in iframe sandbox properties. 
TODO:
Any security constraints with this?
> Add "allow-forms" to support certain B2C scenarios

- lib/msal-core/changelog.md
- lib/msal-core/package.json
- lib/msal-core/src/utils/Constants.ts
Includes:
- Change log for `msal@1.2.1
- Updated package.json and Constants.ts with the `msal js` version `1.2.1`
> 1.2.1 release PR

- lib/msal-browser/src/app/Configuration.ts
- lib/msal-browser/src/crypto/BrowserCrypto.ts
- lib/msal-browser/src/encode/Base64Decode.ts
- lib/msal-browser/src/encode/Base64Encode.ts
- lib/msal-browser/src/interaction_handler/RedirectHandler.ts
- lib/msal-common/src/app/config/ModuleConfiguration.ts
- lib/msal-common/src/app/module/AuthorizationCodeModule.ts
- lib/msal-common/src/auth/Account.ts
- lib/msal-common/src/auth/ClientInfo.ts
- lib/msal-common/src/auth/IdToken.ts
- lib/msal-common/src/auth/ScopeSet.ts
- lib/msal-common/src/auth/authority/Authority.ts
- lib/msal-common/src/auth/authority/AuthorityFactory.ts
- lib/msal-common/src/cache/AccessTokenCacheItem.ts
- lib/msal-common/src/cache/AccessTokenKey.ts
- lib/msal-common/src/cache/CacheHelpers.ts
- lib/msal-common/src/error/ClientAuthError.ts
- lib/msal-common/src/error/ClientConfigurationError.ts
- lib/msal-common/src/error/ServerError.ts
- lib/msal-common/src/logger/Logger.ts
- lib/msal-common/src/response/CodeResponse.ts
- lib/msal-common/src/response/ResponseHandler.ts
- lib/msal-common/src/response/TokenResponse.ts
- lib/msal-common/src/server/ServerAuthorizationCodeResponse.ts
- lib/msal-common/src/server/ServerCodeRequestParameters.ts
- lib/msal-common/src/server/ServerTokenRequestParameters.ts
- lib/msal-common/src/url/UrlString.ts
- lib/msal-common/src/utils/Constants.ts
- samples/VanillaJSTestApp/index_authCode.html
This PR adds ADAL SSO and fixes other SSO scenarios for the Auth Code library.
Please review PR #1208 before this PR for better context.
> Authorization Code Flow for Single Page Applications: SSO Fixes and changes

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/internal.md
- .github/ISSUE_TEMPLATE/question.md
This PR adds the `msal-browser` package as a selection to the issue templates.
> Add msal-browser to Issue Templates

- lib/msal-core/package.json
PR for beta release version change
> Release for version 1.2.2-beta.1

- lib/msal-core/src/UserAgentApplication.ts
- lib/msal-core/src/telemetry/DefaultEvent.ts
- lib/msal-core/src/telemetry/TelemetryManager.ts
- lib/msal-core/src/telemetry/TelemetryTypes.ts
- lib/msal-core/src/utils/Constants.ts
- lib/msal-core/test/telemetry/DefaultEvent.spec.ts
- lib/msal-core/test/telemetry/TelemetryManager.spec.ts
- samples/VanillaJSTestApp/JavascriptSPA/auth.js
- samples/VanillaJSTestApp/JavascriptSPA/authConfig.js
- samples/VanillaJSTestApp/JavascriptSPA/graph.js
add connection speed to telemetry
> add connection speed to telemetry

- lib/msal-core/README.md
Updates CDN links and hashes in README. Waiting for confirmation of upload to CDN from @jmckennon
> Update CDN links and hashes for msal@1.2.2

- lib/msal-common/src/client/DeviceCodeClient.ts
- lib/msal-common/src/response/DeviceCodeResponse.ts
- Map server response to expose device code response as camel case instead of snake case.
- Replace `console.log` with logger
> Update device code client

- samples/UnifiedCacheTestApp/MSAL.html
> Fix response in unified cache sample

- build/postinstall.js
- lerna.json
- lib/msal-browser/README.md
- lib/msal-browser/changelog.md
- lib/msal-browser/docs/acquire-token.md
- lib/msal-browser/docs/configuration.md
- lib/msal-browser/docs/initialization.md
- lib/msal-browser/docs/login-user.md
- lib/msal-browser/docs/logout.md
- lib/msal-browser/docs/request-response-object.md
- lib/msal-browser/docs/token-lifetimes.md
- lib/msal-browser/docs/v1-migration.md
- lib/msal-browser/package-lock.json
- lib/msal-browser/package.json
- lib/msal-browser/src/app/PublicClientApplication.ts
- lib/msal-browser/src/index.ts
- lib/msal-common/README.md
- lib/msal-common/changelog.md
- lib/msal-common/package-lock.json
- lib/msal-common/package.json
- lib/msal-common/test/server/ServerCodeRequestParameters.spec.ts
- lib/msal-common/test/server/ServerTokenRequestParameters.spec.ts
- lib/msal-node/package.json
- samples/VanillaJSTestApp2.0/app/ssoSilent/authConfig.js
This PR adds the final changes for the beta.1 release for 1.0.0 version of @azure/msal-common and the 2.0.0 version of @azure/msal-browser.
> @azure/msal-browser and @azure/msal-common beta.1 release

- lib/msal-angular/package-lock.json
- lib/msal-angularjs/package-lock.json
- lib/msal-core/package-lock.json
- lib/msal-node/package-lock.json
- lib/msal-node/src/crypto/CryptoProvider.ts
- samples/MSALAngularDemoApp/package-lock.json
- samples/angular6-sample-app/package-lock.json
- samples/angular7-sample-app/package-lock.json
- samples/angular8-sample-app/package-lock.json
- samples/angular9-sample-app/package-lock.json
msal node build was failing with some casing issues.
> fix casing issue

- lib/msal-browser/package.json
- lib/msal-common/changelog.md
- lib/msal-common/package-lock.json
- lib/msal-common/package.json
- lib/msal-common/test/server/ServerCodeRequestParameters.spec.ts
- lib/msal-common/test/server/ServerTokenRequestParameters.spec.ts
- lib/msal-node/package.json
Please review #1613 and #1631 before reviewing this PR.
> MSAL Common beta.2 release

- lib/msal-browser/changelog.md
- lib/msal-browser/package-lock.json
- lib/msal-browser/package.json
Please review #1613, #1631 and #1632 before reviewing this PR.
> Release @azure/msal-browser v2.0.0-beta.2

- lib/msal-angular/docs/0.x-1.x-upgrade-guide.md
> Fixed package name in Upgrade Guide

- .github/labeler.yml
- .github/workflows/label.yml
Github Workflow for labeling our PRs based on which files they touch. Could be interesting to try out instead of marking it in the title. 
Labels for:
- Node
- Angular
- Angularjs
- msal-browser
- msal-common
- msal@1.x
- samples
Feel free to share thoughts on this or suggest additional labels
> Auto PR Labeler

- .github/workflows/label.yml
Addresses issues with labeler action
> Fix issues with Labeler Action

- lib/msal-core/src/UserAgentApplication.ts
This PR adds instrumentation through logger messages to acquireTokenPopup and acquireTokenInteractive for msal-core.
> Extend acquireTokenPopup and acquireTokenInteractive instrumentation

- lib/msal-react-native-android-poc/MSALModule/android/.project
- lib/msal-react-native-android-poc/MSALModule/android/.settings/org.eclipse.buildship.core.prefs
- lib/msal-react-native-android-poc/MSALModule/android/src/main/java/com/reactlibrary/MSALModule.java
- lib/msal-react-native-android-poc/SampleApp/App.js
- lib/msal-react-native-android-poc/SampleApp/android/.project
- lib/msal-react-native-android-poc/SampleApp/android/.settings/org.eclipse.buildship.core.prefs
- lib/msal-react-native-android-poc/SampleApp/android/app/.classpath
- lib/msal-react-native-android-poc/SampleApp/android/app/.project
- lib/msal-react-native-android-poc/SampleApp/android/app/.settings/org.eclipse.buildship.core.prefs
- lib/msal-react-native-android-poc/SampleApp/android/app/build.gradle
- lib/msal-react-native-android-poc/SampleApp/android/app/src/main/java/com/sampleapp/MSALModule.java
- lib/msal-react-native-android-poc/SampleApp/android/app/src/main/java/com/sampleapp/MainApplication.java
- lib/msal-react-native-android-poc/SampleApp/index.js
- lib/msal-react-native-android-poc/SampleApp/package-lock.json
- lib/msal-react-native-android-poc/SampleApp/package.json
The PR will add functionality for the app to retrieve an existing signed in account (if there is any) by creating the `getAccount(Promise promise)` ReactMethod. This method will return a map with the account information if it exists and a message detailing the status otherwise. This method and two helper functions (`loadAccount()` and `mapAccount(IAccount account)` were created in MSALModule.java.
Because of Metro Server connectivity issues occurring after last merge, I recreated the SampleApp for the third (and hopefully last) time, which is why there are many random files modified again in this PR. I added functionality to App.js to check for an existing account using the getAccount function when it loads. The Sign In button correspondingly disables if an account is signed in.
For next …
> Retrieve account if already signed in

- lib/msal-react-native-android-poc/MSALModule/android/src/main/java/com/reactlibrary/MSALModule.java
- lib/msal-react-native-android-poc/SampleApp/App.js
- lib/msal-react-native-android-poc/SampleApp/android/app/src/main/java/com/sampleapp/MSALModule.java
- lib/msal-react-native-android-poc/SampleApp/package-lock.json
- lib/msal-react-native-android-poc/SampleApp/package.json
acquireTokenSilent function implemented in MSALModule will return the results from the acquireTokenSilent MSAL Android method, notably the access token. In the sample app, the access token is then used to make a GET request to the Microsoft Graph API with the URL specified in the TextInput. 
The isSharedDevice function has also been added to the module to obtain the Device Mode of the app.
> Get token silently

- .github/workflows/codeql.yml
- lerna.json
- samples/msal-node-extensions/package-lock.json
- samples/msal-node-extensions/package.json
Fixes CodeQL build step and temporarily removes v2 e2e test as the app registration is broken.
> Fix CodeQL build step

- lib/msal-node/README.md
- lib/msal-node/changelog.md
- lib/msal-node/docs/faq.md
Updating msal-node docs:
* Correcting typos
* Adding relevant links for a few flows
> [msal-node] Docs update

- lib/msal-browser/docs/resources-and-scopes.md
Copies over #1957 due to build failure + package-lock file
> Add resources and scopes docs

- lib/msal-node/changelog.md
- lib/msal-node/package.json
- samples/msal-node-extensions/package.json
- samples/msal-node-samples/auth-code/package.json
- samples/msal-node-samples/device-code/package.json
- samples/msal-node-samples/refresh-token/package.json
- samples/msal-node-samples/silent-flow/package.json
> [msal-node] Release alpha.3

- lib/msal-browser/src/request/PopupRequest.ts
- lib/msal-browser/src/request/RedirectRequest.ts
- lib/msal-browser/src/request/SilentRequest.ts
- samples/msal-browser-samples/TypescriptTestApp2.0/src/AuthModule.ts
This PR addresses #2040 by changing SilentFlowRequest to SilentRequest as exported from msal-browser, and updates reference docs to reflect this change.
> Update TypeScript sample with SilentRequest

- extensions/msal-node-extensions/changelog.md
- extensions/msal-node-extensions/package.json
- samples/msal-node-extensions/package-lock.json
- samples/msal-node-extensions/package.json
- Fix issue where binding.gyp is not being uploaded to NPM
> Msal-node-extensions release1.0.0-alpha.2

- change/@azure-msal-angular-2020-08-11-10-47-44-redirect-docs.json
- lib/msal-angular/README.md
> Improve angular handleRedirectCallback documentation

- change/@azure-msal-common-2020-08-11-11-02-18-throttle-docs.json
- lib/msal-common/docs/Throttling.md
Documentation for the throttling feature on #1907
> Documentation for throttling

- .github/workflows/beachball-check.yml
- change/@azure-msal-browser-2020-08-11-13-21-14-fix-handleredirect.json
- change/@azure-msal-common-2020-08-11-13-21-14-fix-handleredirect.json
- lib/msal-browser/src/app/PublicClientApplication.ts
- lib/msal-browser/src/interaction_handler/PopupHandler.ts
- lib/msal-browser/src/interaction_handler/SilentHandler.ts
- lib/msal-common/src/url/UrlString.ts
- lib/msal-common/test/url/UrlString.spec.ts
- samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/test/browser.spec.ts
- samples/msal-browser-samples/VanillaJSTestApp2.0/e2eTests/testRunner.ts
Fixes bugs raised in #2118 : 
- Hash is incorrectly deserialized because '#' symbol is not removed.
- Cache is not cleared if browser back button is pressed
> [msal-browser] Fix bugs in redirect flow

- change/@azure-msal-browser-2020-08-27-13-05-15-fix-hash-2.1.0.json
- lib/msal-browser/README.md
- lib/msal-browser/docs/cdn-usage.md
> Update CDN SRI Hash for 2.1.0

- change/@azure-msal-browser-2020-08-31-11-07-01-docs-updates.json
- lib/msal-browser/FAQ.md
- lib/msal-browser/docs/initialization.md
- lib/msal-browser/docs/v1-migration.md
- Update Migration Guide to reflect changes to `getAllAccounts`
- Add note to FAQ to clarify `handleRedirectPromise` behavior
> Update msal-browser docs

- CODEOWNERS
Beachball change files are causing everyone to get review requests
> Ignore changefiles from CODEOWNERS

- change/@azure-msal-common-2020-09-09-22-34-06-sample-improvement-restructure.json
Replace e-mail in beachball file changes.
> Fix e-mail in beachball files

- lib/msal-browser/docs/initialization.md
Noticed it was 404.
(Also, I swear this isn't a stupid Hacktoberfest PR :) - I'm actually trying to get this working and needed to link to the example)
> Fixing the link to onPageLoad sample

- .github/workflows/build-steps.yml
- .gitignore
- .nycrc
- azure-pipelines.yml
- package.json
- samples/e2eTestUtils/LabClient.ts
- samples/e2eTestUtils/TestUtils.ts
- samples/msal-browser-samples/VanillaJSTestApp2.0/app/customizable-e2e-test/test/browser.spec.ts
- samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/test/browser.spec.ts
- samples/msal-browser-samples/VanillaJSTestApp2.0/app/multipleResources/test/multiple_resources.spec.ts
- samples/msal-browser-samples/VanillaJSTestApp2.0/app/pop/test/browser.spec.ts
- samples/msal-core-samples/VanillaJSTestApp/app/b2c/test/browser.spec.ts
- samples/msal-core-samples/VanillaJSTestApp/app/default/test/browser.spec.ts
- samples/msal-core-samples/VanillaJSTestApp/app/get_access_token_interactively/test/browser.spec.ts
Moves build tasks to Github Actions. This will give us more control to run certain steps conditionally such as: 
- Skip Coveralls and E2E Test steps on PRs coming from forks (we will still need to make some additional changes as the PR will wait indefinitely for a response from coveralls)
- Only build and test relevant libraries to the PR
- Skip build steps for PRs that contain only docs updates, for example
Also makes E2E test screenshots available on failure, making debugging easier
> Add build tasks to Github actions

- extensions/samples/msal-node-extensions/index.js
- samples/msal-node-samples/standalone-samples/auth-code/index.js
- samples/msal-node-samples/standalone-samples/on-behalf-of/web-api/index.js
- samples/msal-node-samples/standalone-samples/on-behalf-of/web-app/index.js
- samples/msal-node-samples/standalone-samples/silent-flow/index.js
- samples/msal-node-samples/standalone-samples/silent-flow/package-lock.json
This PR adds samples for the `Cache Interface` change with `msal-node-extensions` introduced with PR #2348
> Update msal-node samples

- change/@azure-msal-browser-2020-09-10-15-48-23-telemetry-entity.json
- change/@azure-msal-browser-2020-10-12-12-07-01-fix-2373.json
- change/@azure-msal-common-2020-09-10-15-48-23-telemetry-entity.json
- change/@azure-msal-common-2020-09-29-10-21-20-msal-node-update-cache-interface.json
- change/@azure-msal-common-2020-10-14-16-17-24-docs-for-extensions-interface.json
- change/@azure-msal-node-2020-09-29-10-21-20-msal-node-update-cache-interface.json
- change/@azure-msal-node-2020-09-30-10-14-35-add-uuid-dependency.json
- change/@azure-msal-node-2020-10-14-16-17-24-docs-for-extensions-interface.json
- change/@azure-msal-node-extensions-2020-09-29-10-21-20-msal-node-update-cache-interface.json
- lib/msal-common/docs/request.md
- lib/msal-node/docs/configuration.md
- lib/msal-node/docs/initialize-public-client-application.md
- samples/msal-node-samples/standalone-samples/silent-flow/index.js
Updates docs for the latest `msal-node` release
> [msal-node] Docs update for msal-node-alpha-10

- change/@azure-msal-browser-2020-10-15-15-36-17-export-interactionType.json
- lib/msal-browser/src/app/ClientApplication.ts
- lib/msal-browser/src/index.ts
- lib/msal-browser/src/utils/BrowserConstants.ts
> Export InteractionType from msal-browser

- change/@azure-msal-browser-2020-10-21-16-04-50-tnorling-patch-1.json
- lib/msal-browser/README.md
> Remove note about B2C not being supported in msal-browser

- change/@azure-msal-common-2020-11-06-12-29-58-mandate-localAccountId.json
- lib/msal-common/src/account/AccountInfo.ts
- lib/msal-common/src/cache/entities/AccountEntity.ts
This PR makes the `localAccountId` a mandatory property in `AccountInfo`
> Mandate localAccount in AccountInfo

- change/@azure-msal-common-2020-11-09-16-03-49-local-account-id-adfs.json
- lib/msal-common/src/cache/entities/AccountEntity.ts
- lib/msal-common/test/cache/entities/AccountEntity.spec.ts
- lib/msal-common/test/client/ClientTestUtils.ts
- lib/msal-common/test/utils/StringConstants.ts
> add localAccountId for ADFS use cases

- samples/msal-angular-v2-samples/angular10-browser-sample/src/app/app.component.ts
- samples/msal-angular-v2-samples/angular10-browser-sample/src/app/msal/IMsalService.ts
- samples/msal-angular-v2-samples/angular10-browser-sample/src/app/msal/index.ts
- samples/msal-angular-v2-samples/angular10-browser-sample/src/app/msal/msal.service.ts
Updating angular10-browser-sample to reflect changes made in msal-browser and msal-angular-v2
> Update angular10 browser sample 

- change/@azure-msal-react-2020-11-10-09-57-09-msal-react-feature-branch.json
- lib/msal-react/README.md
- lib/msal-react/docs/getting-started.md
- lib/msal-react/package-lock.json
- lib/msal-react/package.json
- Update doc links to point to dev
- Move storybook dependency to devDependencies
> Update react docs links and deps

- lib/msal-angular/README.md
- lib/msal-angular/docs/v2-docs/events.md
- lib/msal-angular/src/msal.guard.spec.ts
- lib/msal-angular/src/msal.guard.ts
- lib/msal-angular/src/msal.interceptor.spec.ts
- lib/msal-angular/src/msal.interceptor.ts
- lib/msal-angular/src/msal.service.spec.ts
This PR:
- Corrects error message in the `msal.interceptor`
- Adds an event doc explaining the event API exposed by msal-browser
- Adds unit tests to `msal.interceptor` and `msal.guard` to increase code coverage
> Angular v2 minor fixes

- lib/msal-react/docs/getting-started.md
Code is missing the import for PublicClientApplication from @azure/msal-browser
> Add missing import for PublicClientApplication

- change/@azure-msal-react-2020-11-24-13-26-34-msal-react-installation-instructions.json
- lib/msal-react/README.md
- samples/msal-react-samples/default/README.md
- samples/msal-react-samples/onPageLoad/README.md
Received some feedback that the installation/sample setup instructions were unclear. This PR aims to address the confusion
> Update msal-react installation instructions

- change/@azure-msal-angular-2020-12-01-15-36-19-angular-change-authorities.json
- lib/msal-angular/README.md
- lib/msal-angular/docs/multi-tenant.md
- lib/msal-angular/docs/v2-docs/1.x-2.x-upgrade-guide.md
This PR:
- Updates MSAL Angular v2 readme to include new samples
- Updates Multi-tenant doc to include dynamically changing authorities
> [msal-angular] Update readme and docs

- samples/msal-node-samples/standalone-samples/auth-code-pkce/index.js
This PR adds the use of the CryptoProvider class to actually generate the PKCE codes in the auth-code-pkce AAD standalone sample and the EndToEndTestApp Auth Code scenario.
> [msal-node] Use CryptoProvider to generate PKCE codes in Auth Code PKCE sample application

- samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/app.component.ts
`BaseAuthRequest` no longer works in this scenario, instead should be either `PopupRequest` or `RedirectRequest`.
> Fix types in Angular v2 B2C sample

- LICENSE
- change/@azure-msal-browser-36e83ab7-73c5-4de1-ad69-f9eb57202fd3.json
- change/@azure-msal-common-7f026b7d-dc53-4a51-8888-852693ae638c.json
- change/@azure-msal-react-280697c4-1775-4599-a99a-879f20704268.json
- experimental/msal-react-native-android-poc/LICENSE
- lib/msal-browser/LICENSE
- lib/msal-common/LICENSE
- lib/msal-react/LICENSE
Adds missing `LICENSE` files to library folders.
> Add missing license files

- change/@azure-msal-angular-425d4dc5-5336-4bad-a3fe-f50a0137217e.json
- lib/msal-angular/docs/v2-docs/configuration.md
This PR updates the msal-angular-v2 configuration doc with details about how to configure msal-angular with platformBrowserDynamic.
> [msal-angular] Update configuration.md with platformBrowserDynamic

- .github/workflows/msal-node-e2e.yml
Adds testing for node versions 12 and 14
Version 10 will be EOL in April and 16 will be released at that time: [https://nodejs.org/en/about/releases/](https://nodejs.org/en/about/releases/)
> Test node versions

- samples/msal-angular-v2-samples/angular11-sample-app/src/app/profile/profile.component.ts
Use of String not recommended minor correction to string in line 7.
> Use of String type

- samples/msal-angular-v2-samples/angular11-sample-app/src/app/detail/detail.component.ts
The use of String is not recommended, this proposal implements this correction in line 7 an 8.
> Minor type error

- roadmap.md
> Update roadmap for FY21Q3

- samples/msal-browser-samples/TypescriptTestApp2.0/src/AuthModule.ts
- samples/msal-browser-samples/TypescriptTestApp2.0/src/UIManager.ts
- samples/msal-browser-samples/TypescriptTestApp2.0/tsconfig.json
> Enable strict in TypeScript sample

- lib/msal-node/docs/configuration.md
This PR fixes links and references in the following `msal-node` docs:
- Configuration.md
> Fix links in msal-node configuration docs

- change/@azure-msal-node-2021-02-17-14-21-20-update-docs-links.json
- lib/msal-node/README.md
- lib/msal-node/docs/configuration.md
- lib/msal-node/docs/faq.md
- lib/msal-node/docs/initialize-confidential-client-application.md
- lib/msal-node/docs/initialize-public-client-application.md
This PR updates node docs in github, repairs old links for library reference (which changed recently) and add FAQs from customer feedback.
> Update MSAL Node Docs with the latest feedback

- samples/msal-react-samples/react-router-sample/README.md
- samples/msal-react-samples/react-router-sample/package.json
- samples/msal-react-samples/react-router-sample/src/authConfig.js
- samples/msal-react-samples/react-router-sample/src/index.js
Update `react-router-sample` to support IE11
> React Sample IE11 Compatibility

- change/@azure-msal-browser-f98a449b-6fbf-47e3-adf3-df18d17fe8a0.json
- lib/msal-browser/README.md
> Update browser Readme wrapper links to Beta

- change/@azure-msal-react-ec0db236-f9ea-4731-8701-9e03185e1ff7.json
- lib/msal-react/README.md
Remove note from React Readme about production level support
> Remove note about production level support in React Readme

- change/@azure-msal-react-4d38a938-61b5-485c-931d-a8b6714a6b92.json
- lib/msal-react/docs/hooks.md
> Fix syntax error in react docs

- change/@azure-msal-browser-05098bc0-039a-435d-a309-1455a230b4ea.json
- lib/msal-browser/docs/logout.md
`redirectMainWindowTo` -> `mainWindowRedirectUri`
> [docs] property name correction

- change/@azure-msal-browser-8181de5f-3c0b-4911-8eb6-80d9f16e438a.json
- lib/msal-browser/docs/accounts.md
`getAllAccounts()` returns an empty array if no account found. Removing the truthiness check (i.e. `!currentAccounts`)
> [docs] code snippet correction

- samples/msal-angular-v2-samples/angular11-b2c-sample/README.md
Very small grammar fix. 
Probably mistyped by accident
> Small fix for the text, removed "first first"

- change/@azure-msal-browser-1e0efd9d-937b-4998-bb17-afa705ae0abf.json
- lib/msal-browser/FAQ.md
See https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3420 for more information.
> Add incompatibility with Azure App Proxy to browser FAQ

- .eslintrc.json
- change/@azure-msal-angular-1a107288-b7ee-4ffa-857e-1997fff45ecf.json
- change/@azure-msal-browser-fdde6973-1c23-4c77-9f54-02d19eb7fcf4.json
- change/@azure-msal-common-4a2588ba-6b01-4b74-8a33-32676c95a47d.json
- change/@azure-msal-node-6c95b8d7-5466-42ad-abd2-14e7e998c038.json
- change/@azure-msal-react-88106e01-7b92-4964-bea3-065cb6e410c5.json
- change/msal-9c8c711f-70ef-4522-b988-7c9f2305c3f0.json
- lib/msal-angular/package-lock.json
- lib/msal-browser/package-lock.json
- lib/msal-browser/src/cache/BrowserCacheManager.ts
- lib/msal-common/src/network/ThrottlingUtils.ts
- lib/msal-common/src/request/ScopeSet.ts
- lib/msal-common/src/url/UrlString.ts
- lib/msal-common/test/url/UrlString.spec.ts
- lib/msal-core/src/ServerRequestParameters.ts
- lib/msal-core/src/UserAgentApplication.ts
- lib/msal-core/src/utils/ResponseUtils.ts
- lib/msal-core/src/utils/TimeUtils.ts
- lib/msal-core/src/utils/UrlUtils.ts
- lib/msal-node/package-lock.json
- lib/msal-react/package-lock.json
It is best practice not to reassign values passed as parameters: https://eslint.org/docs/rules/no-param-reassign
> Enable no-param-reassign lint rule

- .github/workflows/beachball-check.yml
- lib/msal-angular/README.md
- lib/msal-browser/README.md
- lib/msal-common/README.md
- lib/msal-core/README.md
- lib/msal-node/README.md
- lib/msal-react/README.md
Updates each library's Readme with Codecov badge indicating code coverage
> Update code coverage badges in Readmes

- samples/msal-react-samples/b2c-sample/package.json
- samples/msal-react-samples/gatsby-sample/package.json
- samples/msal-react-samples/nextjs-sample/package.json
- samples/msal-react-samples/react-router-sample/package.json
Updates dev samples to use GA version of msal-react
> Update React dev samples to use GA version

- lib/msal-browser/docs/performance.md
Received feedback in #3661 that the docs were confusing about what is and is not supported for B2C use cases. This PR clarifies that only the first section is N/A for B2C
Closes #3661
> Update performance.md to clarify what is not supported for B2C

- .github/workflows/beachball-check.yml
Will skip the beachball workflow on dependabot PRs
> Ignore beachball on dependabot PRs

- lib/msal-browser/docs/logout.md
- samples/msal-angular-v2-samples/angular11-sample-app/src/app/app-routing.module.ts
- samples/msal-angular-v2-samples/angular11-sample-app/src/app/app.component.ts
- samples/msal-angular-v2-samples/angular11-sample-app/src/app/app.module.ts
- samples/msal-angular-v2-samples/angular11-sample-app/src/app/logout/logout.component.html
- samples/msal-angular-v2-samples/angular11-sample-app/src/app/logout/logout.component.spec.ts
- samples/msal-angular-v2-samples/angular11-sample-app/src/app/logout/logout.component.ts
- samples/msal-react-samples/react-router-sample/src/App.js
- samples/msal-react-samples/react-router-sample/src/pages/Logout.jsx
Add docs and samples for how to implement single-sign out via front-channel logout.
> Add docs and samples for front-channel logout

- lib/msal-common/docs/request.md
Typo: broken link of the next page concerning the Response
> Broken link

- lib/msal-angular/README.md
- lib/msal-angular/docs/FAQ.md
- lib/msal-browser/FAQ.md
- lib/msal-browser/README.md
- lib/msal-node/README.md
- lib/msal-node/docs/faq.md
- lib/msal-react/FAQ.md
- lib/msal-react/README.md
* Adds a new FAQ item for using msal.js with Microsoft Graph JS SDK
* Adds more sample links to browser, angular, react and node READMEs
> adding sample links

- lib/msal-react/FAQ.md
Expands msal-react FAQ entry regarding the handling of redirects
> Update redirect guidance in msal-react

- change/@azure-msal-angular-ceb730fd-20a8-4d47-96ba-1610fe016f4b.json
- change/@azure-msal-browser-2ba2953d-faaa-4c86-ae6e-c078026d82c7.json
- lib/msal-angular/src/msal.broadcast.service.spec.ts
- lib/msal-browser/src/app/ClientApplication.ts
- lib/msal-browser/src/app/PublicClientApplication.ts
- lib/msal-browser/src/event/EventHandler.ts
- lib/msal-browser/test/app/PublicClientApplication.spec.ts
- lib/msal-browser/test/event/EventHandler.spec.ts
Moves event code into EventHandler class
> Move event code into EventHandler class

- .beachballrc
- change/@azure-msal-node-extensions-335c98ba-c5f1-4735-ae44-362ee975a140.json
- extensions/docs/msal-node-extensions.md
- extensions/msal-node-extensions/CHANGELOG.json
- extensions/msal-node-extensions/changelog.md
- extensions/msal-node-extensions/package.json
- extensions/msal-node-extensions/src/persistence/PersistenceCachePlugin.ts
- extensions/samples/msal-node-extensions/package.json
Adds `msal-node-extensions` to the beachballrc
> Add extensions to beachball

- lib/msal-browser/FAQ.md
- lib/msal-browser/docs/accounts.md
Updates FAQ and Accounts.md with some frequently asked questions regarding `getAllAccounts`
Closes #3751
> Update accounts FAQ

- change/@azure-msal-browser-d167d84e-f2d8-4c5a-972e-b19fbec6427b.json
- lib/msal-browser/docs/errors.md
- lib/msal-browser/src/error/BrowserAuthError.ts
Adds `monitor_window_timeout` error to the error doc and adds a link to the error message
> Add monitor_window_timeout error to the error doc

- lib/msal-browser/FAQ.md
- lib/msal-node/docs/faq.md
This PR adds an item to msal-browser and msal-node FAQs for creating and provisioning apps via Powershell Graph SDK.
> Add FAQ item for app provisioning via Powershell

- lib/msal-browser/docs/accounts.md
renamed `homehomeAccountId` to `homeAccountId` (extra home)
Thank you all for you hard work
> Tiny typo - update accounts.md

- lib/msal-angular/docs/v2-docs/ie-support.md
Adds steps needed in Angular app to work for IE11.
> Update IE11 docs for MSAL Angular v2

- samples/msal-react-samples/b2c-sample/src/pages/Protected.jsx
- samples/msal-react-samples/b2c-sample/src/ui-components/SignInSignOutButton.jsx
- samples/msal-react-samples/gatsby-sample/src/components/SignInButton.jsx
- samples/msal-react-samples/gatsby-sample/src/components/SignInSignOutButton.jsx
- samples/msal-react-samples/gatsby-sample/src/pages/profile.js
- samples/msal-react-samples/nextjs-sample/pages/profile.js
- samples/msal-react-samples/nextjs-sample/src/ui.jsx
- samples/msal-react-samples/react-router-sample/src/pages/Profile.jsx
- samples/msal-react-samples/react-router-sample/src/pages/ProfileRawContext.jsx
- samples/msal-react-samples/react-router-sample/src/pages/ProfileWithMsal.jsx
- samples/msal-react-samples/react-router-sample/src/ui-components/SignInButton.jsx
- samples/msal-react-samples/react-router-sample/src/ui-components/SignInSignOutButton.jsx
- samples/msal-react-samples/typescript-sample/src/pages/Profile.tsx
- samples/msal-react-samples/typescript-sample/src/ui-components/SignInButton.tsx
- samples/msal-react-samples/typescript-sample/src/ui-components/SignInSignOutButton.tsx
Updates msal-react samples to help clarify questions in #3901 and #3820
> Msal-react sample updates

- change/@azure-msal-angular-3347a981-aa7b-47cc-aa18-24042eadecc1.json
- lib/msal-angular/package.json
Adds license and other missing fields to msal-angular package.json
Addresses #3976
> Add license + missing details to msal-angular

- maintenance/adal-node/lib/mex.js
- maintenance/adal-node/lib/wstrust-response.js
- maintenance/adal-node/lib/xmlutil.js
- maintenance/adal-node/package-lock.json
- maintenance/adal-node/package.json
- maintenance/adal-node/test/wstrust-request.ts
Resolves component governance alerts. See https://github.com/xmldom/xmldom/issues/271#issuecomment-902197883 for more details on xml being renamed.
> Update xmldom in ADAL Node

- README.md
User Voice is deprecated so removed it from the readme
> Remove User Voice from ReadMe

- lib/msal-browser/README.md
> Remove React/Angular beta tags from Browser README

- lib/msal-node/docs/caching.md
Update the caching doc with partition key suggestions
> add partition key suggestions

- samples/msal-node-samples/README.md
This PR adds more sample links to msal-node samples README. 
There are some more which I will add links for after some revisions on them.
> add more sample links

- lib/msal-browser/README.md
These are linked in the FAQ, but I think they should be listed in the main sample list as well.
> Add MSAL Browser plugin sample links to README

- .github/workflows/release_automate.yml
- package.json
This PR:
-Adds an automation workflow to : 
i) Bump package versions
ii) Open/update PR from release-staging to dev 
Trigger event: Merge of feature PR's to dev  branch
> Release automation

- change/@azure-msal-angular-13c49f0e-c3f7-4252-9c26-d74f36f28929.json
- change/@azure-msal-browser-d10dc113-25f8-49a3-b185-6a995d4ac0a5.json
- change/@azure-msal-common-57bd5105-0dd2-4815-92e9-9d55e4dd86bf.json
- change/@azure-msal-node-7de5e9b8-e22a-4484-9f76-4035442cac87.json
- change/@azure-msal-react-cfc1c770-35a9-4cf1-88f4-5c91762cf7a8.json
- change/msal-176fcc6d-11e6-49e0-a923-7521e3c0c0b0.json
- lib/msal-angular/src/public-api.ts
- lib/msal-browser/src/index.ts
- lib/msal-common/src/index.ts
- lib/msal-core/src/index.ts
- lib/msal-node/src/index.ts
- lib/msal-react/src/index.ts
Exports version from each library
Addresses #4122
> Export library versions
