AzureAD/microsoft-authentication-library-for-js

lib/UserAgentApplication.ts
out/msal.js

Bug in call to insertAdjacentHTML('beforeEnd', ...) in UserAgentApplication.ts.
The specifications states that it should be "beforeend", not "beforeEnd":
https://www.w3.org/TR/2011/WD-html5-20110525/apis-in-html-documents.html
This broke the TypeScript pre-processing for me since InsertPosition in lib.es6.d.ts in the typescript node-package is defined as:
type InsertPosition = "beforebegin" | "afterbegin" | "beforeend" | "afterend";
Pull request coming.
Feel free to add a CONTRIBUTING.MD if I'm out of line.

Issue #89 - insertAdjacentHTML('beforeEnd', ...)

---

lib/msal-core/src/UserAgentApplication.ts

Remove prompt=select_account from all login functions, This is to ensure that the MSAL JS library is not hard coding prompt=select_account in its code, completes the fix for https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/489

Remove prompt=select_account from all login functions

---

lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/src/error/AuthError.ts
lib/msal-core/src/error/ClientAuthError.ts
lib/msal-core/src/error/ClientConfigurationError.ts
lib/msal-core/tests/MSAL.spec.ts

Please review PR #582 before reviewing this.
This is the first set of changes in the UserAgentApplication class that utilizes the newly added Error objects for MSAL. These changes include:
- login and acquireToken APIs now throw errors directly for configuration errors, and will return errors in callbacks for all errors returned by the server.
- The openWindow and openPopup functions now use the error objects to communicate popupWindow errors

API Changes: Error - First set of changes to UAA

---

contributing.md
lib/msal-core/.huskyrc
lib/msal-core/package-lock.json
lib/msal-core/package.json

Currently, contributors won't know their code has lint errors until the PR ran the CI. This will allow the contributor to find and fix the lint errors sooner and enforce the lint rules earlier.
It uses [husky](https://github.com/typicode/husky) to run the pre-commit hook.

add pre-commit hook to run lint in msal-core

---

lib/msal-core/src/AuthResponse.ts
lib/msal-core/src/UserAgentApplication.ts

This PR is to fix the following bug:
- calling login/acquireTokenPopup or acquireTokenSilent and also setting the handleRedirectCallbacks function would cause a bug where the redirect callbacks would also be triggered in addition to the promise resolve/reject

Fix Callback Logic for Redirect and Popup

---

lib/msal-core/src/UserAgentApplication.ts

We strip the 'prompt' parameter for silent calls before the server call. This PR removes the code that adds prompt from the user for silent calls, which is redundant.

Ignore 'prompt' parameter for silent calls

---

lib/msal-core/package-lock.json
lib/msal-core/package.json

to prevent non TS projects / ecosystems from breaking from exported TS types

add tslib to dependencies

---

lib/msal-core/src/AccessTokenKey.ts
lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/src/Utils.ts
lib/msal-core/test/Utils.spec.ts

This PR canonicalizes all URIs when using the authority URIs for cache keys. 
I believe this solution will also capture the issue called out by PR #591.

Canonicalize all URIs when storing and retrieving from cache

---

lib/msal-core/.npmignore

it is a fair build artifact to ship to npm

remove dist from npm ignore

---

lib/msal-core/src/UserAgentApplication.ts

This PR is to fix an issue raised here: #670 
This makes the getLoginInProgress function public for the UserAgentApplication object.

Fix API for loginInProgress to be public

---

lib/msal-core/src/Configuration.ts
lib/msal-core/src/UserAgentApplication.ts

Today we are hardcoding the wait time of 500ms when we load an iFrame. Added this to make it configurable.
Future rollout:
To make this more accurate by dynamically checking if the iFrame is loaded and further improvements if possible.

First stab to make the wait time configurable

---

lib/msal-core/src/Account.ts
lib/msal-core/src/Constants.ts
lib/msal-core/src/Storage.ts
lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/src/Utils.ts
lib/msal-core/src/error/ClientAuthError.ts
lib/msal-core/test/Storage.localStorage.spec.ts
lib/msal-core/test/Storage.sessionStorage.spec.ts
lib/msal-core/test/error/ClientAuthError.spec.ts

- Fix the case where the account has no "homeAccountIdentifier" while generating an acquireTokenAccountKey in the code. 
- Minor name change to adhere to "account" instead of "user"
- Test cases modified for Storage class

update acquireTokenAccountKey generation when client_info is empty

---

lib/msal-core/src/UserAgentApplication.ts

Adds the catch calls for the discover endpoints call to make sure we are catching errors in these cases.

Add Endpoint Resolution Error Handling for Redirect Cases

---

lib/msal-core/src/AuthenticationParameters.ts
lib/msal-core/src/Configuration.ts
lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/test/Configuration.spec.ts
lib/msal-core/test/UserAgentApplication.spec.ts

This PR moves the state parameter from the Configuration object to the request object. This more closely follows the Open ID Connect protocol [here](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest). 
Also includes name change for cachedHash.

Move state parameter from Configuration to Request

---

lib/msal-core/src/Constants.ts
lib/msal-core/src/Storage.ts
lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/test/Storage.localStorage.spec.ts
lib/msal-core/test/Storage.sessionStorage.spec.ts
lib/msal-core/test/UserAgentApplication.spec.ts

This PR is a fix for issue #527 where cache keys are not being cleared out. 
A previous PR (#544) was submitted for this, but was failing some use cases. This fix works for manually tested use cases and passes all unit tests.

Fix MSAL cache cleaning method

---

lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/test/UserAgentApplication.spec.ts

This PR is for a fix to remove the guid from the state parameter in the response in successful cases. This allows users to retrieve the state they passed in. This state is tied to the request state passed into the msal APIs.
This PR will also fix the issue raised in #548.

Remove guid from state in response cases

---

lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/test/UserAgentApplication.spec.ts

Previously some tests were failing due to an extra slash being added to the postLogoutRedirectUri. This PR fixes this functionality.

Fix postLogoutUri adding extra slash

---

lib/msal-core/src/Storage.ts
lib/msal-core/test/Storage.localStorage.spec.ts
lib/msal-core/test/Storage.sessionStorage.spec.ts

This PR is created to delete cache entries relating to the MSAL library.

Delete MSAL related cache entries on logout instead of clearing values

---

lib/msal-core/src/UserAgentApplication.ts

This PR is a fix for issue #689. This was a bug introduced with changes to the API.
We now cache the hash briefly before processing the callback in handleRedirectCallback.

Fix: navigateToLoginRequestUrl set to false does not call callbacks

---

lib/msal-core/src/UserAgentApplication.ts

Fix cases where request is undefined for user passed 'state' checks before passing it ServerRequestParameters

Fix cases where request is undefined for user passed 'state' checks

---

lib/msal-core/src/Configuration.ts
lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/test/UserAgentApplication.spec.ts

The library was using a fixed logout url which will not work in all
azure ad cases. According to the oidc specifications the log out url
is published in the discovery document as end_session_endpoint.
This information is fetched and stored in the
TenantDiscoveryResponse.EndSessionEndpoint.
As the discovery property is only required if the OpenId Provider
supports session managment. We will fall back to the original
solution when the property is undefined, null or empty.

fix: use authority.EndSessionEndpoint for logout

---

.gitignore
lib/msal-core/samples/VanillaJSTestApp-b2c/Readme.md
lib/msal-core/samples/VanillaJSTestApp/Readme.md

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>
Library version: 1.0.1
Running the vannila js sample without building `msal-core` results in the sample not working.
Running the samples requires that the build artifacts from `msal-core` are present in the `dist` folder, which requires that project to be built first.

Add note to build msal-core before running samples

---

lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/test/UserAgentApplication.spec.ts

This is a PR to fix the issue described in #733 where the acquireTokenSilent method was throwing errors of the incorrect type. I have updated the type checking and added tests to ensure we are correctly throwing the error.

Fix Issue #733: acquireTokenSilent error not InteractionRequiredAuthError as documented

---

lib/msal-core/src/Configuration.ts

Updating the comments in Configuration.ts because they were not showing the correct parameters.
This was pointed out in issue #778.

Updating Configuration.ts comments to reflect code

---

lib/msal-core/src/Constants.ts
lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/test/UserAgentApplication.spec.ts

When we collect extraQueryParameters from the request object, we sanitize them and remove the sid and login_hint. We should log this so that we aren't silently deleting user given info.

MSAL should log when we remove sid and login_hint from extraQueryParameters

---

lib/msal-angular/package.json
lib/msal-angular/samples/MSALAngularDemoApp/.npmrc
lib/msal-angular/samples/MSALAngularDemoApp/package.json

The main export for the `msal-angular` library was the ES6 version of the library, which is not compatible with IE11 (I was able to reproduce this with the MSAL Angular sample). This updates the library's exports to properly export the CommonJS version of the library by default, with the ES6 version available under `module` ([which matches](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/package.json#L22-L24) the main `msal` package).
Before:
After:

Fix msal-angular exports to properly support IE11, fixes #765 #414

---

issue_template.md

The position of the `</code></pre>` looks misplaced. Move it to a better suiting place

docs: fix position of code end

---

lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/src/Utils.ts
lib/msal-core/test/UserAgentApplication.spec.ts

This PR is to fix the issue raised in PR #790 and add unit tests to ensure future calculations are as expected.
This issue was attempted to be fixed in PR #791 but 791 did not have all of the changes and tests necessary to ensure this use case worked moving forward.
Summary of Changes:
- Changes to expiration time calculation for access token and id token flows
- Utils.expiresIn now returns expiresIn time, not expiresOn
- Utils.setResponseIdToken now also sets expiration
- Simplified saveAccessToken expiration calculation
- Ensure that expiration is always saved as a string in the cache
- Added tests

Fix expiresIn calculation

---

lib/msal-angular/samples/MSALAngularDemoApp/package.json
lib/msal-angularjs/samples/MsalAngularjsDemoApp/package.json
lib/msal-angularjs/samples/MsalAngularjsDemoApp/webpack.config.js

- Fixes #807 where AngularJS sample wasn't building
- Reverted Angular sample to use published version of `msal-angular` until we improve our lerna setup.

Fix angular samples

---

lib/msal-angular/package.json

Reverts the attempted fix for IE11 in #785, which broke aot compiling. This should be merged before any further commits to the Angular package.

Revert IE11 angular fix for main export in #785

---

lib/msal-core/package-lock.json
lib/msal-core/package.json

This will resolve the 179 `npm audit` security warnings due to `mixin-deep` and a couple other transitive dependencies. 
There is still one moderate warning left for `marked` via `typedoc`, [which should be addressed soon](https://github.com/TypeStrong/typedoc/issues/1009).

Regenerate package-lock to pick up latest version of mixin-deep to resolve npm audit warnings

---

lib/msal-angular/src/msal-guard.service.ts

Since the claim name is not required to exist in the id token (https://openid.net/specs/openid-connect-core-1_0.html#IDToken), having the check depending on that claim is breaking some angular users.
In case of this claim name been not returned, the MsalGuard process to acquire a token silently just fails and the redirect to the identity provider takes place.
Fixing the code to check if the idToken is populated than a specific claim.

Removes claim dependency 

---

lib/msal-core/package-lock.json
lib/msal-core/package.json
lib/msal-core/src/AccessTokenKey.ts
lib/msal-core/src/Account.ts
lib/msal-core/src/ClientInfo.ts
lib/msal-core/src/Utils.ts
lib/msal-core/src/telemetry/TelemetryUtils.ts
lib/msal-core/test/Account.spec.ts
lib/msal-core/test/ClientInfo.spec.ts
lib/msal-core/test/Utils.spec.ts

Removes the dependency on `js-base64` due to incompatibility with ES modules, as reported in #746. Replaced base64 encoding functionality with implementation provided on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#Solution_4_%E2%80%93_escaping_the_string_before_encoding_it).
Also removes unused encoding functions that performed similar functionality.

Remove base64-js dependency due to incompatibility with es modules, remove unused encoding functions

---

lib/msal-core/src/ServerRequestParameters.ts
lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/src/utils/UrlUtils.ts
lib/msal-core/test/ServerRequestParameters.spec.ts
lib/msal-core/test/TestConstants.ts
lib/msal-core/test/utils/UrlUtils.spec.ts

Please review PR #805 and #806 before reviewing this one.
This fixes the other part of the issue in #736 where the scopes object that is passed in by the user is being mutated to add "openid" and "profile". This behavior has been moved rectified by using the Array.slice() method.

Fixing issue where input scopes parameter was being mutated

---

lib/msal-core/samples/VanillaJSTestApp/index_renewIdToken.html
lib/msal-core/src/UserAgentApplication.ts

This PR is to fix part of an issue describe in issue #736 where the tokenType in the response for a acquireTokenSilent call which was renewing an id token was incorrectly displaying the "access_token" type.

Fixing issue with tokenType when renewing Id Token

---

lib/msal-core/package-lock.json
lib/msal-core/package.json
lib/msal-core/src/telemetry/TelemetryEvent.ts
lib/msal-core/test/telemetry/ApiEvent.spec.ts
lib/msal-core/test/telemetry/CacheEvent.spec.ts
lib/msal-core/test/telemetry/DefaultEvent.spec.ts
lib/msal-core/test/telemetry/HttpEvent.spec.ts
lib/msal-core/test/telemetry/TelemetryEvent.spec.ts
lib/msal-core/test/telemetry/TelemetryManager.spec.ts
lib/msal-core/test/telemetry/UiEvent.spect.ts

`uuid` library is not compatible with ES modules, and we already have our own implementation of `uuid`, so switch to using that instead.
Fixes #874

Switch to using internal uuid implementation instead of uuid library to support es modules

---

lib/msal-core/package.json

Unit tests are being skipped with the current command for unit tests, as mac does not support wild cards the way windows does. Adding the files to be tested explicitly with this PR.

Support Unit tests to run on all test files in Unix environments

---

lib/msal-core/src/Storage.ts
lib/msal-core/src/UserAgentApplication.ts

This PR fixes two issues in the transient cache (cache items needed during a request-response cycle):
- Nonce is not cleared in the cache in MSAL JS after a response for a token request is processed. This is causing nonce mismatches in some use-cases.
- We are also creating "error" related cache independent of success/failure. This PR restricts the creation of "error" cache only to failure use-cases.

Cache cleanup: Nonce

---

README.md
lib/msal-core/README.md

Simplifies the root README file to remove content duplicated in the README for `msal-core`.

Simplify root README file

---

samples/react-sample-app/src/AuthProvider.js

Adds check for null `loginResponse` in React sample, fixes #1021.

Add null check in React sample to catch if loginResponse is null, fixes #1021

---

lib/msal-core/README.md
samples/VanillaJSTestApp/index.html

This PR will add the Subresource integrity field to our CDN docs to describe how to use this feature.
There is an error message that pops up when you use the resilient import function:
This may warrant further investigation.

Adding SRI Hash to CDN Tags

---

lib/msal-core/README.md
samples/VanillaJSTestApp/index.html

The integrity hashes in the README were incorrect, so I fixed those (verified locally and with https://www.srihash.org/). I also put each script tag into its own code block to make them easier to copy/paste (the bottom script tags were difficult to copy/paste when they are all in the same block).

Fix SRI hashes in readme, also fix some formatting

---

lib/msal-core/src/utils/CryptoUtils.ts
lib/msal-core/test/utils/CryptoUtils.spec.ts

Our base64 decoding was not properly handling when STS generated an id_token for a user with Japanese characters, due to unicode characters. Example id_token included as a test case.
Repro by creating a user with a name with unicode characters (such as those in the test case) and having them sign into the Vanilla JS sample.
Fixes: #985

Fix base64 decoding to properly handle claims with unicode characters such as Japanese

---

lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/test/UserAgentApplication.spec.ts

This PR is to fix an issue raised in #588 where history is not being pushed due to the use of window.location.replace. So far no major issues are identified with using assign instead of replace, but further investigation should be done before merging.

Change location.replace to location.assign

---

lib/msal-core/src/utils/WindowUtils.ts

Following up with SPO update using  the latest beta `msal.1.2.0-beta.2`:
SPO cannot use the most recent version of MSAL as it removes the sandbox attribute from the token fetching iframe. In certain edge cases (such as a missing reply url), a call to retrieve an OAuth token silently will result in ESTS performing a full page direction on the host page (not the iframe). An iframe causing a full page redirect without consent is a terrible experience for most enterprise applications like Sharepoint. Even if the redirection occurs, the end user wouldn’t be able to resolve this configuration issue unless they were the admin user.
To support this we are adding the `sandbox attribute` to our iframe creation, allowing script execution enabling the redirect from the STS.

Add sandbox attribute back to iframes with "allow-scripts"

---

lib/msal-core/README.md

Small fix. Class attr on script tag doesn't add anything as far as I know, and there was an issue raised a while back (#117).

Remove class attribute from script tag

---

lib/msal-browser/.huskyrc
lib/msal-browser/rollup.config.js
lib/msal-browser/src/app/PublicClientApplication.ts
lib/msal-browser/src/index.ts
lib/msal-common/.huskyrc
lib/msal-common/rollup.config.js
lib/msal-common/src/app/module/AuthModule.ts
lib/msal-common/src/app/module/AuthorizationCodeModule.ts
lib/msal-common/src/index.ts

This is the first PR required to be merged into the base branch to support the Authorization Code Flow for Single Page Applications.
This PR introduces [Rollup](https://rollupjs.org/guide/en/) as the module bundler for the Authorization Code Flow instead of webpack as used in the current msal-core implementation. 
- Rollup has node polyfills for import/export, which makes it a little easier to support JS project structures. Webpack does not have these polyfills
- Rollup has support for relative paths, so no need to use path.resolve/path.join
- Use plugins instead of loaders for transformations and bundling in Rollup vs Webpack
- Tree shaking is enabled by default in Rollup, which eliminates dead code and unused exports. There is extra configuration required to do this in Webpack. This …

Authorization Code Flow for Single Page Applications: Rollup Build Files

---

lib/msal-core/src/ServerRequestParameters.ts
lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/src/error/ClientConfigurationError.ts
lib/msal-core/src/index.ts
lib/msal-core/src/utils/CryptoUtils.ts
lib/msal-core/test/ServerRequestParameters.spec.ts
lib/msal-core/test/TestConstants.ts
lib/msal-core/test/error/ClientConfigurationError.spec.ts
lib/msal-core/test/utils/CryptoUtils.spec.ts
lib/msal-core/test/utils/UrlUtils.spec.ts

`msal js` needs to pass the user set correlation-id per request if the application sets it. Currently we are only generating the random guid and ignoring any app passed values.
Todo:
Tests pending

Correlation Id - pass the client set correlation-id to service

---

lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/src/utils/WindowUtils.ts
lib/msal-core/test/UserAgentApplication.spec.ts
lib/msal-core/test/utils/WindowUtils.spec.ts
samples/react-sample-app/src/AuthProvider.js
samples/react-sample-app/src/auth-utils.js

Currently, when `monitorWindowForHash` threw an error, it wasn't properly caught, which resulted in unhandled rejection errors (and the inability for apps to catch and handle these errors on their own). This PR ensures that these errors are caught, and properly passed up to the call site that initiate the request.

Ensure errors thrown when monitoring window are caught and handled

---

lib/msal-core/src/AuthResponse.ts
lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/test/utils/ResponseUtils.spec.ts

This will allow applications to programmatically tell if the token was returned from the cache or from the network, which can be helpful for performance measurements of token requests.

Add fromCache flag to AuthResponse to indicate token was returned from cache

---

lib/msal-core/src/cache/BrowserStorage.ts

This fixes two bugs with cookie storage.
The first occurs if MSAL saves its state in a directory that is not a parent of the directory the user is returned to. The cookie will not be active at this path because the cookie path defaults to the current
path.
The second bug occurs if identity provider does not return from a flow (This can occur if the user closes the tab before being redirected back), and then a new flow is started on a different path is started. Because the default path for cookie is the current paths, and cookies with different paths can have the same key, the msal.state.login cookie is written twice with the same key. Under certain conditions, the wrong cookie can be found when returning from a flow, and the state does not match.
I was unable to write any test cases for …

Fix bugs in cookie storage by setting cookie path

---

lib/msal-browser/src/cache/BrowserStorage.ts
lib/msal-browser/src/error/BrowserAuthError.ts
lib/msal-browser/src/error/BrowserConfigurationAuthError.ts
lib/msal-browser/src/utils/BrowserConstants.ts
lib/msal-common/src/index.ts
lib/msal-common/src/utils/Constants.ts

This PR is a continuation of the work for the Authorization Code Flow for the browser. It introduces the implementation of cache storage in the browser. Please review PR #1133 before this PR.

Authorization Code Flow for Single Page Applications: Browser Storage Implementation

---

samples/VanillaJSTestApp/index_blankPageRedirectUri.html
samples/VanillaJSTestApp/server.js

Sample to demonstrate `redirectUri` as a blank html for `acquireTokenSilent()` calls.

auth.html redirect sample

---

.vscode/settings.json
lib/msal-browser/src/app/Configuration.ts
lib/msal-browser/src/app/PublicClientApplication.ts
lib/msal-common/src/app/config/ModuleConfiguration.ts
lib/msal-common/src/app/config/PublicClientSPAConfiguration.ts
lib/msal-common/src/app/module/AuthModule.ts
lib/msal-common/src/app/module/AuthorizationCodeModule.ts
lib/msal-common/src/index.ts
lib/msal-common/src/logger/Logger.ts
lib/msal-common/src/server/CodeRequestParameters.ts

This PR adds a logger class to the Authorization Code Flow version of the MSAL library. It also removes instances of console.log from the common package.

Authorization Code Flow for Single Page Applications: Adding Logger class

---

.vscode/settings.json
lib/msal-browser/src/app/Configuration.ts
lib/msal-browser/src/app/PublicClientApplication.ts
lib/msal-browser/src/error/BrowserAuthError.ts
lib/msal-browser/src/error/BrowserConfigurationAuthError.ts
lib/msal-browser/src/interaction_handler/IInteractionHandler.ts
lib/msal-browser/src/interaction_handler/RedirectHandler.ts
lib/msal-common/src/app/config/PublicClientSPAConfiguration.ts
lib/msal-common/src/app/module/AuthModule.ts
lib/msal-common/src/app/module/AuthorizationCodeModule.ts
lib/msal-common/src/auth/ScopeSet.ts
lib/msal-common/src/error/ClientAuthError.ts
lib/msal-common/src/error/ClientConfigurationError.ts
lib/msal-common/src/error/ServerError.ts
lib/msal-common/src/request/AuthenticationParameters.ts
lib/msal-common/src/request/TokenExchangeParameters.ts
lib/msal-common/src/response/AuthResponse.ts
lib/msal-common/src/response/CodeResponse.ts
lib/msal-common/src/response/TokenResponse.ts
lib/msal-common/src/server/CodeRequestParameters.ts
lib/msal-common/src/server/ServerAuthorizationCodeResponse.ts
lib/msal-common/src/url/UrlString.ts
lib/msal-common/src/utils/Constants.ts
lib/msal-common/src/utils/ProtocolUtils.ts
lib/msal-common/src/utils/StringUtils.ts
samples/VanillaJSTestApp/index.html
samples/VanillaJSTestApp/index_authCode.html

This PR adds interaction to the Authorization Code Flow version of the MSAL library. 
The current implementation of MSAL determines the type of interaction at processing time instead of when the specific API is called. This PR introduces an IInteractionHandler abstract class which specifies which functions need to be handled when performing different methods of interaction. There will be a separate PR which extends this class for popup scenarios.

Authorization Code Flow for Single Page Applications: Adding Redirect Handling Code

---

lib/msal-core/src/UserAgentApplication.ts

Fixes #1151; Add `urlContainsHash()` to the public interface as documented, instead of `isCallBack()`

Update urlContainsHash() API as a public API as documented

---

lib/msal-common/src/app/module/AuthorizationCodeModule.ts
lib/msal-common/src/cache/CacheHelpers.ts
lib/msal-common/src/error/ClientAuthError.ts
lib/msal-common/src/response/ResponseHandler.ts
lib/msal-common/src/response/TokenResponse.ts
lib/msal-common/src/server/ServerAuthorizationCodeResponse.ts
lib/msal-common/src/server/ServerAuthorizationTokenResponse.ts
lib/msal-common/src/server/ServerTokenRequestParameters.ts

This PR adds the response handling to the authorization code flow for single page applications.
This PR does NOT cover token caching or cache cleanup, those will be addressed in the next immediate PR. Please review PRs #1164 and #1181 before reviewing this PR.

Authorization Code Flow for Single Page Applications: Response Handling Code

---

lib/msal-browser/src/app/PublicClientApplication.ts
lib/msal-browser/src/cache/BrowserStorage.ts
lib/msal-browser/src/error/BrowserAuthError.ts
lib/msal-browser/src/interaction_handler/RedirectHandler.ts
lib/msal-browser/src/utils/BrowserConstants.ts
lib/msal-common/src/app/module/AuthorizationCodeModule.ts
lib/msal-common/src/cache/AccessTokenCacheItem.ts
lib/msal-common/src/cache/AccessTokenKey.ts
lib/msal-common/src/cache/AccessTokenValue.ts
lib/msal-common/src/cache/CacheHelpers.ts
lib/msal-common/src/error/ClientAuthError.ts
lib/msal-common/src/response/ResponseHandler.ts
lib/msal-common/src/utils/Constants.ts
lib/msal-common/src/utils/TimeUtils.ts
samples/VanillaJSTestApp/index_authCode.html

This PR add token caching and cache cleanup after requests to the authorization code flow for single page applications. 
Please review PRs #1181 and #1183 before this PR.

Authorization Code Flow for Single Page Applications: Token Caching and Cleanup

---

lib/msal-browser/src/app/Configuration.ts
lib/msal-browser/src/app/PublicClientApplication.ts
lib/msal-browser/src/interaction_handler/PopupHandler.ts
lib/msal-browser/src/interaction_handler/RedirectHandler.ts
lib/msal-common/src/app/config/ModuleConfiguration.ts
lib/msal-common/src/app/config/PublicClientSPAConfiguration.ts
lib/msal-common/src/app/module/AuthModule.ts
lib/msal-common/src/app/module/AuthorizationCodeModule.ts
lib/msal-common/src/auth/ScopeSet.ts
lib/msal-common/src/cache/AccessTokenKey.ts
lib/msal-common/src/cache/AccessTokenValue.ts
lib/msal-common/src/cache/CacheHelpers.ts
lib/msal-common/src/error/ClientAuthError.ts
lib/msal-common/src/index.ts
lib/msal-common/src/request/AuthenticationParameters.ts
lib/msal-common/src/request/ClientRequestParameters.ts
lib/msal-common/src/request/TokenRenewParameters.ts
lib/msal-common/src/response/CodeResponse.ts
lib/msal-common/src/response/ResponseHandler.ts
lib/msal-common/src/server/ServerAuthorizationCodeResponse.ts
lib/msal-common/src/server/ServerCodeRequestParameters.ts
lib/msal-common/src/server/ServerRequestParameters.ts
lib/msal-common/src/server/ServerTokenRequestParameters.ts
lib/msal-common/src/url/UrlString.ts
lib/msal-common/src/utils/Constants.ts
lib/msal-common/src/utils/TimeUtils.ts
samples/VanillaJSTestApp/index_authCode.html

This PR adds the silent flow and logout to the library. The implementation of ADAL SSO and other SSO features is included in a later PR.
This PR also enables CSP in our sample applications. This improves the security of our samples, and should be included in documentation moving forward.

Authorization Code Flow for Single Page Applications: Silent Flow and Logout

---

lib/msal-browser/src/app/PublicClientApplication.ts
lib/msal-browser/src/interaction_handler/PopupHandler.ts
lib/msal-common/src/app/module/AuthorizationCodeModule.ts
lib/msal-common/src/cache/CacheHelpers.ts
lib/msal-common/test/app/config/PublicClientSPAConfiguration.spec.ts
lib/msal-common/test/app/module/AuthModule.spec.ts
samples/VanillaJSTestApp/index_authCode.html

This PR adds cleanup for different popup related errors, as well as window navigation actions such as redirect and refresh. This does not affect token acquisition, but does force users to be aware that handleRedirectCallback() should not be used with the popup APIs, as it will cause the window to handle the response in the popup, rather than the main window.
This should fix the issue raised in #1231.

Authorization Code Flow for Single Page Applications: Cleanup Popup Flows and Window Nav

---

lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/src/utils/WindowUtils.ts

Eliminate setTimeOut() calls when a user sets `navigateFrameWait` in `msal` config  to `0` to improve performance.
Currently MSAL JS while loading iframes for silent calls always makes an async call to `loadFrame` and slowing down performance intensive apps. This is introduced for IE which requires delay in loading a frame and the modern browsers seem to do alright with no time out (feedback from users who have this in production).
This PR would thus allow for better perf by eliminating the asynchronous call for the modern browsers when the timeout is set to `0`

render iframe synchronously if the user sets zero navigateToFrame time

---

lib/msal-core/src/cache/AuthCache.ts
lib/msal-core/test/Storage.localStorage.spec.ts

This PR fixes #1333 where the `msal-core` lib assumes that "state" is always a GUID and does not have a delimiter within itself.
We fixed this by making sure that the `guid` the `msal` attaches before sending a request to `server` is always appended at the beginning and we rectify the split logic to reflect this.
Note: tests will be added before merging this.

Split the state correctly for temp cache clearance

---

lib/msal-core/src/authority/AuthorityFactory.ts
lib/msal-core/src/authority/B2cAuthority.ts
lib/msal-core/test/authority/AuthorityFactory.spec.ts
lib/msal-core/test/authority/B2cAuthority.spec.ts

- Moves B2CTrustedHostList to B2cAuthority class to fix circular dependency with AuthorityFactory

[msal-core] Fix circular dependency for B2C Authority

---

lib/msal-node/src/cache/Storage.ts
lib/msal-node/src/client/ClientApplication.ts
lib/msal-node/test/config/ClientConfiguration.spec.ts
lib/msal-node/tsconfig.json

Set strictNullChecks = true for MsalNode. Using null assertion operator, as we ensure that all configuration values are assigned default values when we build the configuration, so we can assume that they will not be null.

[msal-node] Switch strictNullChecks: true for msal-node

---

lib/msal-browser/docs/initialization.md

Fix example URIs ending in ".con" over ".com", which causes copied examples to not work

Fix typos in initialization.md

---

lib/msal-core/src/authority/Authority.ts
samples/react-sample-app/package-lock.json
samples/react-sample-app/package.json

Not all promise polyfills (such as the one that ships with Create React App, which is used in the React sample) come with a `.finally`, so removing it to prevent breakages.

Remove .finally from discoverendpoint promise chain as it isnt available in all promise polyfills

---

lib/msal-browser/package-lock.json
lib/msal-browser/package.json
lib/msal-browser/src/index.ts
lib/msal-browser/src/types/AuthCallback.ts
lib/msal-browser/tsconfig.json
lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/src/XHRClient.ts
lib/msal-core/src/telemetry/HttpEvent.ts
lib/msal-core/src/telemetry/TelemetryManager.ts
lib/msal-core/src/telemetry/TelemetryUtils.ts

This PR fixes the issues raised in #1510 and #1507. 
Types were not being exported because of import elision in Typescript. Typescript version has been updated to 3.8.x and import/export is fixed.
BrowserAuthError and BrowserConfigurationError and their corresponding message classes have now also been added to the exports to allow for better error handling.
Also includes minor changes to msal-core to fix linting errors.

[msal-browser] Fix issues in @azure/msal-browser where types are not exported correctly

---

lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/test/UserAgentApplication.spec.ts

Using loginStartPage as the condition for setting the account cache prevented access tokens from being cached in interactive flows since loginStartPage is always set. This PR changes the conditional check to more accurately differentiate between login calls and access token calls.
This PR fixes issues: 
#1505 
#1509

[msal-core] Fix token caching for acquireToken calls

---

lib/msal-core/src/ServerRequestParameters.ts

Restore a null test removed in https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/bf86b898d120760e4a1c62126becd088deb78b55#diff-01b40b5f69b6021ac7031ce85ef0d452L120-L123
This addresses #1411, #1237, and #1254. I don’t know why some of these type errors are passing compilation as they should be breaking it?
Untested, edited code in browser window.
There should probably be some tests added to CI for this as the last version that works seems to be 1.1.3.

Check if request is null in populateQueryParams

---

lib/msal-browser/src/app/PublicClientApplication.ts
samples/VanillaJSTestApp2.0/app/onPageLoad/auth.js
samples/VanillaJSTestApp2.0/app/onPageLoad/authConfig.js
samples/VanillaJSTestApp2.0/app/onPageLoad/graph.js
samples/VanillaJSTestApp2.0/app/onPageLoad/index.html
samples/VanillaJSTestApp2.0/app/onPageLoad/test/template.spec.ts
samples/VanillaJSTestApp2.0/app/onPageLoad/ui.js

This PR fixes an issue raised in #1497 where calling loginRedirect on page load will cause the application to go into a redirect loop. 
This PR adds an API which allows applications using the redirect flow to utilize and notify their application that MSAL is done loading.

[msal-browser] Add pattern for login on page-load

---

lib/msal-common/test/client/AuthorizationCodeClient.spec.ts
lib/msal-common/test/client/BaseClient.spec.ts
lib/msal-common/test/client/DeviceCodeClient.spect.ts
lib/msal-common/test/client/RefreshTokenClient.spec.ts
lib/msal-common/test/client/SPAClient.spec.ts
lib/msal-common/test/config/Configuration.spec.ts
lib/msal-common/test/config/PublicClientSPAConfiguration.spec.ts
lib/msal-common/test/mochaSetup.js
lib/msal-common/test/request/RequestValidator.spec.ts
lib/msal-common/test/server/RequestParameterBuilder.spec.ts

Add commonly used imports to mochaSetup.js

Clean up imports in msal-common tests

---

lib/msal-angular/src/msal.service.ts
lib/msal-angular/tests/MSALSpec.ts
lib/msal-angular/tests/TestConstants.ts

The order in which the angular handleRedirectCallback determines whether to return a success or failure is backwards. A response object will always be populated with at least state, whereas error will only be populated if there is an error. Therefore we need to check for error to be truthy first and if not, only then do we return a success.
This PR fixes: #1406 and #1554

[msal-angular] Fix error broadcast in handleRedirectCallback

---

lib/msal-browser/package.json

The types file location was pointing to the wrong place. This PR updates the file location.

Fix types file location in msal-browser

---

lib/msal-browser/src/config/Configuration.ts
lib/msal-browser/test/config/Configuration.spec.ts
lib/msal-common/src/client/SPAClient.ts
lib/msal-common/src/config/ClientConfiguration.ts
lib/msal-common/src/index.ts
lib/msal-common/src/request/ScopeSet.ts
lib/msal-common/test/config/Configuration.spec.ts

This PR fixes an issue where the default system configuration in `msal-common` was being overwritten by the undefined values in `msal-browser`. This PR adds the default system values to `msal-common` exports and uses them in the `msal-browser` package.
This should fix #1623.

[msal-common][msal-browser] Fix issue where config was being overwritten by undefined values

---

lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/src/utils/UrlUtils.ts
lib/msal-core/test/UserAgentApplication.spec.ts
lib/msal-core/test/utils/UrlUtils.spec.ts
package-lock.json
package.json

This PR fixes #1602 by ensuring query strings don't disrupt the redirect flow. Msal compares the `currentUrl` to the `loginRequestUrl` to determine if another redirect is required. 
**Previous Behavior:** The `currentUrl` was being stripped of both hash and query string whereas the `loginRequestUrl` was left as is. This was fine for hash routing strategies because we had another check to see if a hash was present in the `loginRequestUrl`. However, with a query string present the Url comparison check will always fail and the token response hash will not be processed.
**New Behavior:** Both `currentUrl` and `loginRequestUrl` will be normalized and compared using the full url minus any non-msal hash to determine if a redirect is needed. If they are equal (final page has been reached), add …

Fix redirection to urls containing query strings

---

.github/workflows/stale.yml

Stale Action we enabled on Friday was only running in debug mode. This PR enables the Action and updates the messages that will be commented on the Issue/PR when the label is applied.

Stale Action - Remove debug flag and update messages

---

.github/workflows/stale.yml

Adds `Enhancement` and `Known-issue` labels to be exempt from being marked stale

Update exempt labels from Stale Issue Bot

---

lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/test/UserAgentApplication.spec.ts
samples/VanillaJSTestApp/app/get_access_token_interactively/auth.js
samples/VanillaJSTestApp/app/get_access_token_interactively/authConfig.js
samples/VanillaJSTestApp/app/get_access_token_interactively/graph.js
samples/VanillaJSTestApp/app/get_access_token_interactively/index.html
samples/VanillaJSTestApp/app/get_access_token_interactively/test/browser.spec.ts
samples/VanillaJSTestApp/app/get_access_token_interactively/ui.js
samples/VanillaJSTestApp/e2eTests/testRunner.ts

This PR fixes #1755, #1713 and #1763
`loginStartPage` is only being cached for login calls. This means that when `navigateToLoginRequestUrl: true` and calling `acquireTokenRedirect` the user will be redirected back to the root of their application and the response hash will not be processed.
Diff largely due to new Sample + E2E tests. Relevant code changes are just in `UserAgentApplication`

Fix processing and redirection of acquireTokenRedirect

---

build/sdl-tasks.yml
lib/msal-core/src/UserAgentApplication.ts

This PR adds instrumentation through logger messages to the following functions in msal-core:
- `loginPopup`
- `loginRedirect`
- `acquireTokenRedirect`
- `ssoSilent`
- `urlContainsHash`
- `authResponseHandler`
- `authErrorHandler`
- `logout`
- `logoutAsync`
- `clearCache`
- `clearCacheForScope`

Extend login and logout instrumentation

---

lib/msal-react-native-android-poc/MSALModule/android/src/main/java/com/reactlibrary/MSALModule.java
lib/msal-react-native-android-poc/SampleApp/App.js
lib/msal-react-native-android-poc/SampleApp/android/app/src/main/java/com/sampleapp/MSALModule.java

signOut() was added to MSALModule and the sample app. Calling the function within a react-native app will attempt to sign out the user currently signed in. If successful, a boolean "true" will be returned. If not, an exception is thrown that is logged in the Android console and passed to the react native app. 
The sample app was updated to utilize signOut() and clears the user's data within the app upon completion. A new user is able to sign in immediately afterwards.

signOut() function added

---

lib/msal-react-native-android-poc/MSALModule/android/src/main/java/com/reactlibrary/Constants.java
lib/msal-react-native-android-poc/MSALModule/android/src/main/java/com/reactlibrary/MSALModule.java
lib/msal-react-native-android-poc/SampleApp/App.js
lib/msal-react-native-android-poc/SampleApp/android/app/src/main/java/com/sampleapp/Constants.java
lib/msal-react-native-android-poc/SampleApp/android/app/src/main/java/com/sampleapp/MSALModule.java

This PR adds the acquireToken function to MSALModule and utilizes it in the sample app. 
So far, the module should be able to wrap MSAL for Android's single account mode functions for AAD, which is the minimum project goal I set for myself. It would be good to get all this polished before I move on to more features, which could include multiple accounts mode.

Complete Single Account Mode MSAL for React Native

---

lib/msal-browser/src/cache/BrowserStorage.ts
lib/msal-browser/test/app/PublicClientApplication.spec.ts
lib/msal-browser/test/cache/BrowserStorage.spec.ts
lib/msal-common/src/authority/TrustedAuthority.ts
lib/msal-common/src/utils/StringUtils.ts
lib/msal-common/test/client/AuthorizationCodeClient.spec.ts
lib/msal-common/test/client/ClientTestUtils.ts
lib/msal-common/test/utils/StringConstants.ts

This PR fixes a couple issues
- Cookies were not encoded before being saved, which resulted in cookie key:value errors when setting b64 values with trailing `=` characters. 
- State was being double encoded in some cases on the server-side, adding an additional `decodeURIComponent` should fix those issues.

[msal-browser] Fix encoding issues

---

lib/msal-common/src/request/ScopeSet.ts
lib/msal-common/test/request/ScopeSet.spec.ts

This PR fixes an issue where scopes passed with `extraScopesToConsent` would not be added in a trimmed and lower-case format.

[msal-common] Fix issue where extraScopesToConsent was not appending scopes correctly

---

samples/VanillaJSTestApp2.0/Readme.md

Link on row 9 is broken because of an hyphen

Fix to "Pre-requisites" link

---

lib/msal-browser/src/app/PublicClientApplication.ts
lib/msal-common/src/url/UrlString.ts
samples/msal-browser-samples/VanillaJSTestApp2.0/app/ssoSilent/authConfig.js

This PR fixes cache items not being cleaned in certain scenarios:
- When a silent iframe call failed
- When the back button is used in a redirect flow
- When the handleRedirectPromise() function is not used

Cache cleanup v2

---

lib/msal-browser/test/app/PublicClientApplication.spec.ts
lib/msal-common/src/cache/CacheManager.ts
lib/msal-common/src/cache/interface/ICacheManager.ts
lib/msal-common/src/client/AuthorizationCodeClient.ts
lib/msal-common/src/client/RefreshTokenClient.ts
lib/msal-common/src/client/SilentFlowClient.ts
lib/msal-common/src/response/ResponseHandler.ts
lib/msal-common/test/client/AuthorizationCodeClient.spec.ts

This PR fixes an issue where expiration wasn't being calculated correctly.

[msal-common] Fix expiration calculation for AuthenticationResult object

---

lib/msal-browser/README.md
lib/msal-common/docs/Accounts.md

Docs for Accounts usage:
* `getAccounts()` and `getAccountByUsername()` usage
* Guidance on multiple accounts use cases
Note:
Part of the doc will be replaced with `typedocs` links when `msal-common` typedocs are available. cc @jo-arroyo

Add documentation for Accounts

---

lib/msal-browser/src/app/PublicClientApplication.ts
lib/msal-browser/src/config/Configuration.ts
lib/msal-browser/src/index.ts
lib/msal-browser/test/config/Configuration.spec.ts
samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/authConfig.js
samples/msal-browser-samples/VanillaJSTestApp2.0/app/multipleResources/authConfig.js
samples/msal-browser-samples/VanillaJSTestApp2.0/app/onPageLoad/authConfig.js
samples/msal-browser-samples/VanillaJSTestApp2.0/app/ssoSilent/authConfig.js

Adds a private logger instance to PublicClientApplication. Also makes the default loggerCallback a noop, as apps should only get console.logs if they implement them.

Instantiate Logger instance for PublicClientApplication

---

lib/msal-browser/src/app/PublicClientApplication.ts

This PR updates the constructor to remove async authority creation and have it occur only on the first API call.

[msal-browser] Move authority initialization from constructor

---

lib/msal-browser/src/app/PublicClientApplication.ts

This PR removes the checks that the constructor does to clean the cache. All redirect handling logic is exclusively done in handleRedirectPromise().

[msal-browser] Remove cache cleanup code from constructor

---

lib/msal-react-native-android-poc/android/src/main/java/com/reactlibrary/MSALModule.java
lib/msal-react-native-android-poc/package.json
samples/msal-react-native-android-poc-sample/package-lock.json
samples/msal-react-native-android-poc-sample/package.json

Modified the React method`getAccount()` to use the MSAL Android method `getAccountAsync()` instead of `getAccount`. 
Although `getAccount` was functionally working fine before, using an async function would make the corresponding React method truly async and it would match the styling of the other React methods. 
'getAccount` calls `getAccountAsync()`, which takes a callback as a parameter. This `CurrentAccountCallback` is implemented with the same resolve values that the original `getAccount` would have. 
`loadAccount` is still kept as a private method for the `acquireTokenSilent` function but is no longer used in `getAccount`.

Use getAccountAsync instead of getAccount

---

lib/msal-browser/src/app/PublicClientApplication.ts

Particularly as this is a change from MSAL 1.x functionality, this removes two out-dated comments indicating that redirectUri and postLogoutRedirectUri can be functions.

Minor comment change for redirect URIs

---

lib/msal-angular/README.md

This PR updates the msal-angular README with links to msal-angular samples, as well as fixing syntax errors in the README.
This addresses issue #1931

Update Angular README with correct sample links

---

lib/msal-common/src/response/ResponseHandler.ts
lib/msal-common/test/response/ResponseHandler.spec.ts
lib/msal-common/test/utils/StringConstants.ts

Fixes a bug where an error is thrown if an access token is not returned by the server, such as a scenario where login is called with an empty request object (we only expect id_token in the response)

Check if tokens are returned before attempting to create token entity

---

lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/test/UserAgentApplication.spec.ts

Fixes a bug where an error is thrown stating that `this.authResponseCallback` is not a function. This can happen in redirect scenarios when `handleRedirectCallback` has not been implemented and an error occurs before redirecting away from the app. For example: when throwing an Interaction in Progress error
Addresses #1877 and a question about this raised in #1674

Fix Redirect Error Callback

---

lib/msal-browser/src/interaction_handler/PopupHandler.ts

This PR prevents PopUp window position offsets from being negative by using `Math.max()` in order to make the top and left offsets 0 if they are negative immediately before they are added to the calculated position.
Fixes #1928

[msal-browser] Add negative offset value prevention for popup windows

---

lib/msal-browser/src/app/PublicClientApplication.ts
lib/msal-browser/src/interaction_handler/RedirectHandler.ts
lib/msal-browser/test/app/PublicClientApplication.spec.ts
lib/msal-browser/test/utils/StringConstants.ts

When not providing a request object to loginRedirect, error occurs because it expects `redirectStartPage`. This PR fixes this.

Fix empty request

---

samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/test/browser.spec.ts
samples/msal-browser-samples/VanillaJSTestApp2.0/app/multipleResources/test/multiple_resources.spec.ts
samples/msal-browser-samples/VanillaJSTestApp2.0/e2eTests/LabClient.ts
samples/msal-browser-samples/VanillaJSTestApp2.0/e2eTests/TestUtils.ts

- Moves some commonly used functions to separate TestUtils file
- Improves validation of tokens in the cache by inspecting the contents rather than relying on a count
- Extends the account selector for future use cases such as testing B2C or ADFS

Refactor E2E Tests

---

lib/msal-browser/src/app/PublicClientApplication.ts
lib/msal-browser/src/interaction_handler/RedirectHandler.ts
lib/msal-browser/src/utils/BrowserUtils.ts
lib/msal-browser/test/app/PublicClientApplication.spec.ts
lib/msal-common/src/url/UrlString.ts

Builds on #2045, refactors and fixes the following bugs in the redirect flow:
- #2055 State mismatch error when calling `handleRedirectPromise` multiple times
- `currentUrl` and `loginRequestUrl` being evaluated as not equal if one has a trailing slash and the other does not
- When `loginRequestUrl` is not in the cache, msal redirects to the homepage but would not process the hash

handleRedirect fixes

---

lib/msal-core/src/utils/WindowUtils.ts
lib/msal-core/test/utils/WindowUtils.spec.ts
samples/msal-core-samples/VanillaJSTestApp/e2eTests/testRunner.ts

Fixes #2071
When a user provides their own `state` as part of the request, `checkIfBackButtonIsPressed` throws a state mismatch because it splits the cached request `"redirect"|libraryState|userState` on the delimiter and takes the last value. This results in `libraryState|userState` being compared to just `userState`. This PR fixes the behavior by dropping the first value after splitting and then rejoining the remaining values with the delimiter.

Fix back button behavior

---

lib/msal-browser/src/app/PublicClientApplication.ts
lib/msal-common/test/client/DeviceCodeClient.spec.ts
samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/auth.js
samples/msal-browser-samples/VanillaJSTestApp2.0/app/ie11-sample/auth.js
samples/msal-browser-samples/VanillaJSTestApp2.0/app/ie11-sample/authConfig.js
samples/msal-browser-samples/VanillaJSTestApp2.0/app/multipleResources/auth.js
samples/msal-browser-samples/VanillaJSTestApp2.0/app/navigateToLoginPage/auth.js
samples/msal-browser-samples/VanillaJSTestApp2.0/app/onPageLoad/auth.js
samples/msal-browser-samples/VanillaJSTestApp2.0/app/ssoSilent/auth.js

Fixes an issue where promises were not resolving in silent flow APIs, which wasn't clearing cache correctly. Should also fix #2089.

[msal-browser] Fix Promises in PCA APIs

---

change/@azure-msal-common-2020-08-11-16-45-31-fix-id-token-claims-type.json
lib/msal-common/src/account/IdTokenClaims.ts
lib/msal-common/src/response/AuthenticationResult.ts

This PR:
- Fixes #2084 
- Changes the type for AuthenticationResult.idTokenClaims from StringDict to generic object in order to allow non-string values for ID Token claims

[msal-common] Fix ID Token Claims type

---

change/@azure-msal-common-2020-08-20-11-36-50-Fix-Telem-CacheHit-bug.json
lib/msal-common/src/client/SilentFlowClient.ts
lib/msal-common/test/client/SilentFlowClient.spec.ts

If ServerTelemetryManager is not instantiated, getting a token from cache in SilentFlowClient would throw an error due to the `incrementCacheHits` call not being gated. This PR fixes that bug and adds a test for getting token from cache

Fix Telemetry Cache Hit Bug

---

lib/msal-core/src/utils/CryptoUtils.ts
lib/msal-core/test/utils/UrlUtils.spec.ts

This PR:
- Removes wrapping call to decodeURIComponent in CryptoUtils.deserialize to avoid over-decoding user state
- Adds unit test to deserialize hash to make sure state values are only decoded once.
- Fixes #2088

[msal-core] Fix invalid state issue by removing second layer of URL decoding

---

change/@azure-msal-common-2020-08-21-16-04-20-scopes-lookup.json
lib/msal-common/src/cache/CacheManager.ts
lib/msal-common/src/request/ScopeSet.ts
lib/msal-common/test/cache/CacheManager.spec.ts
samples/msal-browser-samples/VanillaJSTestApp2.0/e2eTests/testRunner.ts
samples/msal-core-samples/VanillaJSTestApp/app/adfs/test/browser.spec.ts
samples/msal-core-samples/VanillaJSTestApp/app/b2c/test/browser.spec.ts
samples/msal-core-samples/VanillaJSTestApp/e2eTests/testRunner.ts

* This PR is added to ignore `offline_access` in the scopes lookup while filtering tokens in cache lookup.
* We will follow up this with having a agreed strategy on all `OIDC` scopes soon.

[msal-common] Ignore offline_access in scopes lookup

---

change/@azure-msal-browser-2020-08-25-16-59-10-fix-unit-tests.json
lib/msal-browser/test/app/PublicClientApplication.spec.ts

Not awaiting resolution of `acquireTokenPopup` was causing overlap in tests, meaning sometimes the telemetry cache entry for failed requests had multiple values when it only expected one.

Fix msal-browser tests causing build to fail intermittently

---

lib/msal-browser/src/cache/DatabaseStorage.ts
lib/msal-browser/src/crypto/BrowserCrypto.ts
lib/msal-browser/src/crypto/CryptoOps.ts
lib/msal-browser/src/utils/BrowserConstants.ts
lib/msal-browser/src/utils/BrowserStringUtils.ts
lib/msal-browser/test/app/PublicClientApplication.spec.ts
lib/msal-browser/test/cache/BrowserStorage.spec.ts
lib/msal-browser/test/crypto/CryptoOps.spec.ts
lib/msal-browser/test/interaction_handler/RedirectHandler.spec.ts
lib/msal-browser/test/utils/BrowserProtocolUtils.spec.ts
lib/msal-browser/test/utils/StringConstants.ts

This PR is a follow up to PR #2153, and includes the `msal-browser` implementation of the token signing and key storage APIs introduced in the previous code.
Specifically, this PR includes the following:
- Browser implementation of key storage using IndexedDB
- Browser implementation of jwt token signing

AT Proof-Of-Possession #3: Browser Implementation of token signing and key storage

---

change/@azure-msal-browser-2020-09-10-15-56-58-add-loginHint-to-iframed-acquireTokenSilent.json
change/@azure-msal-common-2020-09-10-15-56-58-add-loginHint-to-iframed-acquireTokenSilent.json
lib/msal-browser/src/app/ClientApplication.ts
lib/msal-browser/src/app/PublicClientApplication.ts
lib/msal-browser/test/app/PublicClientApplication.spec.ts
lib/msal-common/src/client/AuthorizationCodeClient.ts
lib/msal-common/src/client/RefreshTokenClient.ts
lib/msal-common/src/client/SilentFlowClient.ts
lib/msal-common/src/request/AuthorizationUrlRequest.ts
lib/msal-common/test/client/AuthorizationCodeClient.spec.ts
lib/msal-common/test/client/RefreshTokenClient.spec.ts
lib/msal-common/test/client/SilentFlowClient.spec.ts
lib/msal-common/test/utils/StringConstants.ts

- Move `acquireTokenByRefreshToken` to `RefreshTokenClient`
- `acquireTokenSilent` uses:
1. `acquireCachedToken` on `SilentFlowClient`
2. `acquireTokenByRefreshToken` on `RefreshTokenClient`
3. `ssoSilent` if refresh token is expired
- `account` is added as optional parameter on `AuthorizationUrlRequest` to accommodate the lack of `loginHint` and `sid` on the `SilentFlowRequest` object.
- Auth Code Url parameter builder prefers `sid` over `loginHint` and will generate `login_hint` from `account.username` if neither are provided.

acquireTokenSilent calls ssoSilent

---

change/@azure-msal-browser-2020-09-14-16-48-24-accountinfo-name.json
change/@azure-msal-common-2020-09-14-16-48-24-accountinfo-name.json
lib/msal-browser/test/app/PublicClientApplication.spec.ts
lib/msal-common/src/account/AccountInfo.ts
lib/msal-common/src/cache/entities/AccountEntity.ts
lib/msal-common/test/client/RefreshTokenClient.spec.ts
lib/msal-common/test/client/SilentFlowClient.spec.ts

Fixes #2147
This adds the  optional `name` field to the `AccountInfo` type, pulling it directly from `AccountEntity`. This exposes it to our users through `getAllAccounts()`

Expose name field in AccountInfo

---

change/@azure-msal-common-2020-09-23-11-49-08-public-network-interface.json
change/@azure-msal-node-2020-09-23-11-49-08-public-network-interface.json
lib/msal-common/src/cache/CacheManager.ts
lib/msal-common/src/cache/interface/ICacheManager.ts
lib/msal-node/src/index.ts

AzureSDK has a requirement to customize their network calls and `msal-common` already has an interface which facilitates it. This PR exports the needed interfaces in `msal-node` to limit the package dependency.

Network Interface is exported for custom http calls in AzureSDK

---

change/@azure-msal-node-2020-10-14-14-29-17-msal-node-export-errors.json
lib/msal-node/src/index.ts

This PR adds 'error' types in msal-node export types for users to discern between different error types and to be able to use `instanceOf` to classify their errors.

Msal node export errors

---

change/@azure-msal-browser-2020-10-20-14-41-15-unsubscribe-event.json
lib/msal-browser/src/app/ClientApplication.ts
lib/msal-browser/src/app/IPublicClientApplication.ts
lib/msal-browser/test/app/PublicClientApplication.spec.ts

- Adds an API to remove an event callback
- Changes `eventCallbacks` array to a Map with a guid key
- `addEventCallback` returns an id
- Fixes login vs acquireToken logic which had the comparison backwards

Add removeEventCallback API

---

samples/msal-angular-v2-samples/angular10-browser-sample/src/app/msal/msal.guard.ts

The current msal.guard in the Angular 10 sample code does not use the scopes passed into the MsalGuardConfig during redirect login since it overwrites the given scopes with an empty array.
This updates the sample msal.guard to make sure all the values from the MsalGuardConfig are respected.

Fix loginRedirect Angular 10 Sample Code

---

change/@azure-msal-common-2020-10-23-08-46-53-set-default-headers.json
lib/msal-common/src/client/DeviceCodeClient.ts

`Content-type` and `Telemetry` headers are missing in `device code flow` as we are not calling the default headers API correctly. Fixing the issue with this PR.
Note: We mock all our network calls in unit tests and hence couldn't catch this in our testing. 
Todo:
Adding these in end-to-end tests is a good idea. Will try to see if the current framework allows this.

[msal-common] Add missing default headers to device code

---

change/@azure-msal-common-2020-10-26-10-27-03-fix-telemetry-bug.json
lib/msal-common/src/telemetry/server/ServerTelemetryManager.ts
lib/msal-common/src/utils/Constants.ts
lib/msal-common/test/telemetry/ServerTelemetryManager.spec.ts

If an error is thrown that is not type `AuthError` (i.e. doesn't have the `errorCode` property) the ServerTelemetryManager will save this error in the cache as `null`. A recent update surfaced this problem when trying to access the length property of `null` and thus throwing an error.
This PR addresses this bug by putting additional fallbacks in place to ensure we always store a string in the cache and a value is type string before we attempt to get the `length`
Fixes #2476, #2474

Fix ServerTelemetry maxErrorsToSend bug

---

.github/workflows/build-steps.yml
.github/workflows/msal-browser-e2e.yml
.github/workflows/msal-core-e2e.yml
.github/workflows/msal-node-e2e.yml

No need to run build or tests when PRs only make docs updates. This PR updates the workflows to ignore `.md` files

Prevent markdown file updates from triggering build pipeline

---

lib/msal-react/docs/hooks.md

This PR fixes the invalid links at the start of the MSAL React hooks documentation page. All index links needed `-hook` appended to them in order to link with the headers on the page.

Fix inline links in React hooks documentation page

---

change/@azure-msal-browser-2020-11-20-16-19-36-remove-console-logs-tests.json
change/@azure-msal-common-2020-11-20-16-19-36-remove-console-logs-tests.json
lib/msal-browser/test/config/Configuration.spec.ts
lib/msal-browser/test/interaction_handler/InteractionHandler.spec.ts
lib/msal-browser/test/interaction_handler/PopupHandler.spec.ts
lib/msal-browser/test/interaction_handler/RedirectHandler.spec.ts
lib/msal-browser/test/interaction_handler/SilentHandler.spec.ts
lib/msal-common/test/config/ClientConfiguration.spec.ts

Removes logger messages output to the console when running unit tests

Remove console.logs from unit tests

---

change/@azure-msal-common-2020-11-25-14-41-39-fix-2652.json
lib/msal-common/src/client/OnBehalfOfClient.ts
lib/msal-common/test/client/OnBehalfOfClient.spec.ts

Fixes  https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2652
`async` was missing and the test mock returned `null` instead of a Promise of `null`.

fix: AzureAD/microsoft-authentication-library-for-js#2652

---

change/@azure-msal-react-2020-11-24-09-32-04-react-ssosilent-example.json
lib/msal-react/docs/hooks.md

Fix example to show useMsalAuthentication returns an object instead of an array, using the `InteractionType` enum, and how to display the logged in user.

Update msal-react ssoSilent example

---

change/@azure-msal-react-2020-11-24-11-41-00-react-ssr-fix.json
lib/msal-react/src/MsalProvider.tsx
lib/msal-react/src/hooks/useIsAuthenticated.ts

Updates state value defaults to static values instead of relying on `msal-browser` APIs.
Server Side Render - State **always** defaults to `accounts: []` and `isAuthenticated: false` because window object is not available
Client Side Render - State can default to any valid value because window object is now available and a user could potentially be signed in
This causes a mismatch between the Server Side Render and the initial Client Side Render
All renders default to `[]` and `false`, then `useEffect` hook calls `msal-browser` APIs to get the current value on mount.
This ensures the Server Side Render matches the initial Client Side Render and the Client is still able to get the correct state.

Fix msal-react SSR warning server/client mismatch

---

samples/msal-angular-v2-samples/README.md
samples/msal-angular-v2-samples/angular10-browser-sample/README.md
samples/msal-angular-v2-samples/angular10-browser-sample/src/app/app.module.ts

This PR:
- Updates the `angular10-browser-sample` with information about `@azure/msal-angular@2`
- Adds a readme file to `msal-angular-v2-samples` folder with links to samples
- Changes default interaction type in sample to use redirects. 
This PR addresses and will close issue #2630 .

Update angular10-browser-sample readme

---

change/@azure-msal-common-2020-11-30-15-46-35-common-logger-clone.json
lib/msal-common/src/logger/Logger.ts
lib/msal-common/test/logger/Logger.spec.ts

This PR adds a `clone` function to the `Logger.ts`. This function will be used by wrapper libraries (such as `msal-angular`) to add a new Logger to log wrapper library-specific logs, while using the same logger configurations set up for `msal-browser`. This PR also adds unit tests. 
Note: This function has also been duplicated on the `msal-angular-v2` branch.

[msal-common] Add clone to Logger

---

lib/msal-angular/src/msal.guard.spec.ts
lib/msal-angular/src/msal.guard.ts
lib/msal-browser/src/index.ts

This PR updates the guard to check if redirectUri is set to a page with MSAL guard and logs a warning. 
Also updates exports from msal-browser.
Changes being made to msal-browser are duplicated on the `dev` branch in #2680

[msal-angular] Add redirectUri check to guard

---

change/@azure-msal-browser-2020-12-02-09-16-10-browser-new-exports.json
lib/msal-browser/src/index.ts

This PR matches the changes being done in #2677, adding additional exports to msal-browser `index.ts`, to be used in the msal-angular-v2 guard.

[msal-browser] Add exports to index.ts

---

samples/msal-angular-v2-samples/angular11-sample-app/.browserslistrc
samples/msal-angular-v2-samples/angular11-sample-app/package-lock.json
samples/msal-angular-v2-samples/angular11-sample-app/package.json
samples/msal-angular-v2-samples/angular11-sample-app/src/polyfills.ts
samples/msal-angular-v2-samples/angular11-sample-app/tsconfig.json

This PR updates the angular11-sample-app with IE11 compatibility. No changes needed to be made to the msal-angular-v2 library.
This branched off the `angular-replace-minimatch` branch, and will be merged there first, before merging to `msal-angular-v2`.

[msal-angular] Angular 11 sample IE11 compatibility

---

change/@azure-msal-browser-2020-12-03-14-11-51-update-browser-exports.json
lib/msal-browser/src/index.ts

This PR updates msal-browser's exports, as required by changes made to msal-angular-v2 on PR #2683, in order for it to be available at the next release.

[msal-browser] update browser export

---

lib/msal-angular/docs/v2-docs/1.x-2.x-upgrade-guide.md
lib/msal-angular/docs/v2-docs/initialization.md
lib/msal-angular/ng-package.json
lib/msal-angular/package-lock.json
lib/msal-angular/package.json
lib/msal-angular/src/msal.guard.ts
lib/msal-angular/src/msal.interceptor.spec.ts
lib/msal-angular/src/msal.interceptor.ts
lib/msal-browser/src/index.ts
samples/msal-angular-v2-samples/angular11-sample-app/.browserslistrc
samples/msal-angular-v2-samples/angular11-sample-app/package-lock.json
samples/msal-angular-v2-samples/angular11-sample-app/package.json
samples/msal-angular-v2-samples/angular11-sample-app/src/polyfills.ts
samples/msal-angular-v2-samples/angular11-sample-app/tsconfig.json

This PR:
- Removes `minimatch` and `path` from msal-angular dependencies
- Replaces minimatch usage with `StringUtils.matchPattern` from msal-browser
- Updates documentation on wildcard matching
- Improves interceptor tests related to wildcard matching
- IE11 compatibility added to angular11-sample-app
Changes made to msal-browser are mirrored on #2693.

[msal-angular] replace minimatch

---

change/@azure-msal-common-2020-12-07-13-07-17-fix-empty-query-string.json
lib/msal-common/src/url/UrlString.ts
lib/msal-common/test/url/UrlString.spec.ts
samples/msal-browser-samples/VanillaJSTestApp2.0/app/customizable-e2e-test/test/browser.spec.ts

When a redirect is initiated from a page with an empty ? in the url it will lead to an infinite loop
`clearHash` will remove the empty ? before comparison of loginRequestUrl to current url so the 2 will never be equal
This PR fixes this by removing the ? from the end of a url before comparison

Fix empty query string bug

---

.github/workflows/typedoc.yml
lib/msal-angular/tsconfig.json
package.json

This action will automatically build and deploy typedocs on pushes to master branch.
You can see it worked here: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/gh-pages/ref

Add action to deploy typedocs

---

change/@azure-msal-node-e1216fab-db96-4b5e-b319-17f3bcffa13b.json
lib/msal-node/src/client/ClientAssertion.ts
lib/msal-node/test/client/ClientAssertion.spec.ts
lib/msal-node/test/utils/TestConstants.ts

It is common for certs exported from pfx to contain newlines. For example, OpenSSL exports certs in the format:
```
-----BEGIN CERTIFICATE-----
MIIFSDCCBDCg........................................
IqNDl5bnkmR0........................................
eUd4y23epjUW........................................
BnozMiiGCHuG........................................
jGqq8qpdA6wT........................................
...
-----END CERTIFICATE-----
```
The regex in `ClientAssertion.parseCertificate` was unable to parse such certs due to the `.` term's default behavior of not matching newlines (even when the multiline flag is present). This is fixed by the addition of the s (dotall) flag.
Fixes https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2720

ClientAssertion.parseCertificate - handle newlines

---

change/@azure-msal-angular-798c02ae-d006-4c63-980b-0d5d9fe50148.json
change/@azure-msal-browser-fd4bda27-4447-4533-857c-ef1a34dc9cb0.json
lib/msal-angular/docs/v2-docs/events.md
lib/msal-browser/docs/events.md
samples/msal-angular-v2-samples/angular10-browser-sample/src/app/msal/msal.service.ts
samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/app.component.ts

This PR: 
- Updates the msal-angular v2 docs with information on how to handle EventError, in response to issue #2761
- Updates the `angular11-b2c-sample` with type checking 
- Updates `angular10-browser-sample` with correct request parameters from `@azure/msal-browser@2.8`, in response to issue #2763

[msal-angular] Update docs and samples

---

change/@azure-msal-browser-8173e10f-1d8e-4169-83b5-6febcecf6134.json
lib/msal-browser/src/cache/BrowserCacheManager.ts

Adds an internal in-memory storage object to BrowserCacheManager which can be used for data internal to msal that does not need to be stored in local/session storage and does not need to persist across page loads or PCA instances.
Examples: 
- Authority metadata
- Broker responses before being passed down to child

Add internal in-memory storage to BrowserCacheManager

---

samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/app.component.ts

This PR addresses a comment made on [this commit](https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/f149f86c9a42997d620019c1d1a3da2d1d172f6c) about imports in the Angular v2 B2C sample, and updates the imports accordingly. It also changes a type-casting warning in the same file.

Update imports for Angular v2 B2C sample

---

change/@azure-msal-browser-2ca47cd6-90a9-4988-b2c3-d0fbeacecdad.json
lib/msal-browser/src/app/ClientApplication.ts
samples/msal-browser-samples/VanillaJSTestApp2.0/app/customizable-e2e-test/test/browser.spec.ts

This PR adds support for relative uris on `redirectStartPage` using the same API that was used to support this for `redirectUri` and `postLogoutRedirectUri`
Closes #2855

Extend relative uri support to redirectStartPage

---

change/@azure-msal-react-992bfddf-7f4e-4ec3-8641-0b02cd157268.json
lib/msal-react/docs/getting-started.md

Resolves #2887 
The example code does not include a `useAccount` import that is later relied upon.
This PR adds the `useAccount` import from `@azure/msal-react` which results the error.

Issue-2887 useAccount import missing from quickstart documentation

---

change/@azure-msal-browser-68164171-9fe4-48ad-a670-53fd594999f9.json
lib/msal-browser/src/app/ClientApplication.ts
lib/msal-browser/src/cache/BrowserCacheManager.ts
samples/msal-browser-samples/VanillaJSTestApp2.0/app/customizable-e2e-test/test/localStorage.spec.ts

In version 2.10.0 we made a change to store temporary cache items in `sessionStorage` regardless of what storage option was configured for tokens. When making this update we missed 2 functions which clear temporary storage in cases of failure, such as closing an open popup or clicking the browser back button during a redirect. This caused a regression when using `localStorage` potentially resulting in `interaction_in_progress` errors.
This PR updates 2 temporary cache clear functions to clear `sessionStorage` and updates the E2E tests that didn't catch this bug.

Fix temp cache cleanup when using localStorage

---

change/@azure-msal-angular-f0faf086-e53d-459c-bf10-c0a51c839224.json
lib/msal-angular/src/msal.interceptor.spec.ts
lib/msal-angular/src/msal.interceptor.ts
samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/app.module.ts

There is a known issue with the B2C service where it is only capable of issuing RTs that work for one resource, and calling the token endpoint with a mismatched RT/AT resource combo results in teh service returning a successful response with a null access token. To mitigate, the interceptor will invoke interaction, which will acquire a new RT for the relevant resource.

Invoke interaction if MSAL Interceptor returns null access token

---

change/@azure-msal-angular-0de29d0d-210a-4af4-81b3-bf865c46e95d.json
lib/msal-angular/src/msal.guard.ts

This PR updates the MSAL Guard to check the version of Angular used by applications to determine whether to return a `loginFailedRoute` or boolean in the `canLoad` interface. 
This PR addresses issue #2923.

[msal-angular] Update guard with version detection for canLoad

---

lib/msal-angular/src/constants.ts
lib/msal-angular/src/msal.broadcast.service.ts
lib/msal-angular/src/public-api.ts
lib/msal-browser/src/event/EventMessage.ts
lib/msal-browser/src/index.ts
lib/msal-browser/src/utils/BrowserConstants.ts
lib/msal-browser/test/event/EventMessage.spec.ts
lib/msal-react/src/MsalContext.ts
lib/msal-react/src/MsalProvider.tsx
lib/msal-react/src/components/MsalAuthenticationTemplate.tsx
lib/msal-react/src/hooks/useAccount.ts
lib/msal-react/src/hooks/useIsAuthenticated.ts
lib/msal-react/src/hooks/useMsalAuthentication.ts
lib/msal-react/src/index.ts
lib/msal-react/src/utils/Constants.ts
lib/msal-react/test/MsalProvider.spec.tsx

This PR:
- Adds `getInteractionStatusFromEvent` to msal-browser
- Updates msal-react and msal-angular to use `getInteractionStatusFromEvent`
- Adds unit tests
This PR will merge into `angular-b2c-sample-change` #2885 before merging to dev.

Add getInteractionStatusFromEvent to msal-browser

---

change/@azure-msal-browser-04c92788-a1e3-4dac-ba88-85c8f9be715d.json
lib/msal-browser/docs/errors.md
lib/msal-browser/src/app/IPublicClientApplication.ts
lib/msal-browser/src/error/BrowserConfigurationAuthError.ts
lib/msal-browser/test/app/IPublicClientApplication.spec.ts
lib/msal-browser/test/app/PublicClientApplication.spec.ts

`PublicClientApplication` stub errors were throwing the constructor rather than the error message. This PR fixes this and also:
- Adds tests
- Adds explanation to the errors doc
- Adds aka.ms vanity link to the errors doc in the error message (open to other suggestions for the link name)

Fix stub errors not throwing properly

---

lib/msal-react/docs/getting-started.md

Added `{}` as default value in `useAccount()` because an error is otherwise thrown on first render due to `accounts[0]` being undefined until a successful authentication has been achieved. See #2773 where this issue has been reported.

Check useAccount() for undefined accounts[0] value

---

change/@azure-msal-browser-ad675bda-ab43-4b3d-935d-1688d2913cca.json
lib/msal-browser/src/interaction_handler/PopupHandler.ts

This ensures that we are enabling scrollbars for popup interactions. Modern browsers seem to set this by default, but IE11 does not. This change was originally done in v1 in #1426, and we forgot to bring it forward to v2. This is an accessibility consideration, namely.

Ensure scrollbars are enabled for browser popups

---

change/@azure-msal-angular-449f8e13-b11b-4dfc-92b3-e3e1542431ea.json
lib/msal-angular/karma.conf.js
lib/msal-angular/src/msal.guard.spec.ts
lib/msal-angular/src/msal.guard.ts

When `false` is returned from an Angular Guard, the default behavior is for the app to be redirect back to the home page. In theory, `loginRedirect` could take longer than expected, causing the app to be redirected to the home page and then redirected to the login screen. This can be problematic if the home page uses a guard, or automatically redirects to a page use the guard. This should help mitigate this race condition by letting the `loginRedirect` operation complete first (which should happen, as that promise is set to take 30 seconds, but the redirect should always happen first, not giving the promise a chance to resolve).

Await loginRedirect in MSAL Guard to prevent race conditions

---

change/@azure-msal-common-164c2c31-d950-4d43-9601-a63101917787.json
lib/msal-common/src/request/CommonDeviceCodeRequest.ts
samples/msal-node-samples/standalone-samples/device-code/index.js

This PR:
- Calls out the unit for the `timeout` configuration option in `CommonDeviceCodeRequest` type as seconds
- Increases the `device-code` sample default timeout from 5 to 20 seconds
- Addresses #3016 and #3017

[msal-common] Device Code Timeout documentation and sample update

---

change/@azure-msal-angular-7c84ff5a-7773-4dde-a551-3665adb6e468.json
lib/msal-angular/package.json

Msal-Angular has a preinstall script that runs `npm-force-resolutions` to force npm to install certain versions of dependencies. A recent update to the `npm-force-resolutions` package is causing this preinstall script to fail, so this PR forces the version of `npm-force-resolutions` to 0.0.3.

Update msal-angular preinstall script to force npm-force-resolutions version

---

change/@azure-msal-common-ba830074-164e-4e0f-8188-9d5d3f44c276.json
lib/msal-common/src/cache/CacheManager.ts
lib/msal-common/src/client/RefreshTokenClient.ts
lib/msal-common/src/client/SilentFlowClient.ts
lib/msal-common/test/client/SilentFlowClient.spec.ts

Fixes #3045.
`acquireTokenSilent()` was seeing cache misses due to `offline_access` scope not being present, this PR fixes the issue (adds on to previous PR #2969)

Fix OIDC Scopes Caching Issue

---

change/@azure-msal-browser-38f0f734-e4bf-4dd5-9c4e-ef1379f478d6.json
lib/msal-browser/src/app/ClientApplication.ts
lib/msal-browser/test/app/PublicClientApplication.spec.ts
lib/msal-browser/test/utils/StringConstants.ts

Multiple concurrent calls to `handleRedirectPromise` can cause race conditions and confusing errors when the first invocation clears temporary cache before the 2nd can read it. The official recommendation up until now has been "dont call handleRedirectPromise more than 1 time per page load" but this can be confusing and easy to overlook when using frameworks (react, angular, etc.) that may re-render components and call `handleRedirectPromise` again unexpectedly.
This PR aims to solve this once and for all by having all invocations of `handleRedirectPromise` on a single `PublicClientApplication` instance return the same promise and ensure that the hash processing logic is only run once.
Note: This does not solve scenarios where your page has multiple instances of `PublicClientApplication` …

Memoize handleRedirectPromise

---

extensions/msal-node-extensions/src/persistence/FilePersistence.ts
extensions/msal-node-extensions/src/persistence/IPersistence.ts

We have a mismatch in the return types for the function `load()` in `FilePersistence.ts` and other implementations of `IPersistence` header. This PR corrects it.

Add the correct type to `load()` method in IPersistence class

---

.github/workflows/build-steps.yml
.github/workflows/msal-angular-e2e.yml
.github/workflows/msal-browser-e2e.yml
.github/workflows/msal-core-e2e.yml
.github/workflows/msal-node-e2e.yml
.github/workflows/msal-react-e2e.yml

Adds a step to CI and E2E workflows to cancel in-progress and queued workflow runs on the same branch. This will help speed things up when you make several back to back pushes to a PR, ensuring that previous workflow runs aren't holding up the most recent push due to concurrency limits.

Update workflows to cancel in-progress runs

---

samples/msal-node-samples/standalone-samples/device-code/readme.md

Noticed that a link was broken when following along with the steps.  Verified that the link now links to the right place.
Not sure why there is a whitespace change on line 115? I made this change on the web GUI.

Update slight typo in README

---

.github/issue_template_bot.json

The `.x` in some of the label search strings is causing the bot to miss labeling issues that specify a specific version e.g. `msal@1.4.4`
Searching for just the package name should allow for better pattern matching

Update Issue bot labeler

---

change/@azure-msal-angular-34d95922-3876-421c-89f0-0b025bfb762b.json
lib/msal-angular/src/msal.service.spec.ts
lib/msal-angular/src/msal.service.ts

This PR updates `handleRedirectObservable` in the MsalService. The previous code was clearing the `redirectHash` and was causing problems with caching when `handleRedirectObservable` is called multiple times. This change also allows an optional hash to be passed in to `handleRedirectObservable` if necessary.

Update msal-angular service redirect hash handling

---

change/@azure-msal-browser-d3c10e55-3c44-480c-9389-d20067eed81e.json
lib/msal-browser/docs/working-with-b2c.md

Updates working with B2C doc to remove outdated information and adds note about known issue with passing clientId as scope

Update B2C docs with ClientId workaround

---

samples/msal-node-samples/device-code/test/device-code-aad.spec.ts
samples/msal-node-samples/device-code/test/device-code-adfs.spec.ts

This PR adds 5 seconds to the jest timeout for device code tests that are currently timing out intermittently

Increase device code tests timeout

---

change/@azure-msal-angular-8e4f15fb-20b5-442a-97c4-a5bff75e8292.json
change/@azure-msal-browser-556df87b-50db-4e57-9008-07cbeac3c298.json
lib/msal-angular/docs/v2-docs/events.md
lib/msal-browser/docs/events.md
lib/msal-browser/src/index.ts
samples/msal-angular-v2-samples/angular10-sample-app/src/app/home/home.component.ts
samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/home/home.component.ts
samples/msal-angular-v2-samples/angular11-sample-app/src/app/home/home.component.ts

This PR:
- Exports `PopupEvent` from msal-browser
- Updates msal-browser docs to include `PopupEvent`
- Updates msal-angular samples to cast event payload to correct types (fixes CI test failures)
- Updates msal-angular event docs to include casting examples and instructions

Export EventPopup and fix event type casting in msal-angular samples

---

.eslintrc.json
package-lock.json
package.json

This PR adds Angular-specific lint rules to MSAL to lint msal-angular.
See [angular-eslint](https://github.com/angular-eslint/angular-eslint) for more details. [Base](https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/src/configs/base.json) and [recommended rules](https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.json) added.

Add angular-eslint rules

---

change/@azure-msal-browser-37bc3bd2-2a8d-42ff-8b42-82a2ac1ab5f0.json
lib/msal-browser/docs/token-lifetimes.md

Received some feedback that the wording in the docs around refresh token renewal was confusing. Making this more explicit.

Update docs to clarify RT lifetime

---

.github/actions/issue_template_bot/dist/index.js
.github/actions/issue_template_bot/main/index.ts

Fixes error thrown when payload doesn't contain `changes` property (this was added last week to prevent parsing issues transferred from another repo)

Fix bug in issue bot

---

lib/msal-browser/docs/resources-and-scopes.md

Original text:
`The intended recipient of an **Access Token** is represented by the `aud` claim; in case the value for the `aud` claim does not mach the resource`
Updated text:
`The intended recipient of an **Access Token** is represented by the `aud` claim; in case the value for the `aud` claim does not match the resource`

Fixed a minor typo - `match` was spelled as `mach`

---

change/msal-ba6e8b60-d254-4653-ae66-605a883bebac.json
lib/msal-core/src/cache/BrowserStorage.ts
lib/msal-core/test/Storage.localStorage.spec.ts
lib/msal-core/test/Storage.sessionStorage.spec.ts

Ensures cookie names and values are encoded to prevent control characters from being sent to servers.
Should match v2 implementation: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/789428d8fd6fc6c69656e9f0802a874fa09d1d07/lib/msal-browser/src/cache/BrowserCacheManager.ts#L500-L531

Encode control characters in cookies set by MSAL.js v1

---

lib/msal-react/docs/getting-started.md

I noticed that an import statement ended with `l` instead of `;`.

Fix missing semicolon in code example

---

change/@azure-msal-angular-b0172103-6866-4f25-9d89-4084d829edd3.json
lib/msal-angular/docs/v2-docs/known-issues.md
lib/msal-angular/src/msal.guard.spec.ts
lib/msal-angular/src/msal.guard.ts

When the redirect URI was set to a page with the MSAL Guard, the guard could end up navigating the user to `/#code`, even though it should be cleared from the URL when processing the redirect. This change makes sure the user isn't navigated back to a url with the `#code=` hash response still in the url.

Prevent MSAL Guard from navigating app to url with code hash

---

change/@azure-msal-browser-332c1b46-7af3-4c8e-a6d8-d34fc6f729fa.json
lib/msal-browser/src/cache/BrowserCacheManager.ts
lib/msal-browser/test/cache/BrowserCacheManager.spec.ts

Since 2.10, temp cache items have been stored in session storage or in memory, instead of local storage (if configured). This can result in unexpected cache misses when upgrading between versions. This change will look in local storage if temp cache items aren't found in session/memory storage.

Look for temp cache items in local storage as fallback

---

change/@azure-msal-browser-c4954852-5365-4234-bd2f-74bd57bbc04a.json
lib/msal-browser/FAQ.md
lib/msal-browser/docs/working-with-b2c.md

The empty access token bug on the B2C service has been fixed. This PR removes the workaround from our docs as it's no longer relevant.

Remove B2C empty access token workaround

---

change/@azure-msal-react-ba499dcd-7a30-4bcc-a96f-2d4c127ba56c.json
lib/msal-react/package.json
lib/msal-react/src/components/UnauthenticatedTemplate.tsx
lib/msal-react/test/components/UnauthenticatedTemplate.spec.tsx

When signing in using redirects applications may flash Unauthenticated content momentarily while the redirect response is being processed. This PR fixes this behavior by preventing `UnauthenticatedTemplate` from rendering children until after `handleRedirectPromise` is finished.
Fixes #3538

Prevent UnauthenticatedTemplate from rendering when handleRedirectPromise is in progress

---

change/@azure-msal-angular-85214804-df42-45d1-8491-8485605eef32.json
lib/msal-angular/.gitignore
lib/msal-angular/src/msal.guard.spec.ts
lib/msal-angular/src/msal.guard.ts
samples/msal-angular-v2-samples/angular10-sample-app/src/app/app.component.ts
samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/app.component.ts
samples/msal-angular-v2-samples/angular11-sample-app/src/app/app.component.ts
samples/msal-angular-v2-samples/angular12-sample-app/src/app/app.component.ts

In #3506, this scenario was only handled for path routing. Furthermore, return `false` in the guard is not the correct behavior. Instead, it should return a url tree to the page without the hash response.

Properly handle MSAL guard on redirect uri for hash and path routing

---

change/@azure-msal-node-eddce1b6-c91e-4ca9-a7aa-15e787c799a1.json
lib/msal-node/docs/key-vault-managed-identity.md

This PR adds some tips for converting `pfx` formatted certificates to `pem` to msal-node certificates documentation.

add guidance for pfx to pem conversion

---

.github/workflows/beachball-check.yml
.github/workflows/build-steps.yml
.github/workflows/label.yml
.github/workflows/msal-angular-e2e.yml
.github/workflows/msal-browser-e2e.yml
.github/workflows/msal-core-e2e.yml
.github/workflows/msal-node-e2e.yml
.github/workflows/msal-react-e2e.yml
.github/workflows/npm-audit.yml

Github Actions recently added a native check for concurrent workflows running on the same PR and cancel any in progress workflow.
This PR replaces the existing 3rd party check with Githubs check which runs when the workflow is _queued_ instead of when it actually _starts_.

Workflows use native concurrency check

---

lib/msal-core/package-lock.json
lib/msal-core/package.json

This PR:
- Updates `handlebars` to v4.7.7 in msal-core

[msal-core] Update handlebars from 4.7.6 to 4.7.7

---

samples/msal-angular-v2-samples/angular11-b2c-sample/README.md

Typo on app.module.ts filename

Fix 'app.module.ts' typo in README.md 

---

samples/msal-node-samples/auth-code/test/auth-code-aad.spec.ts
samples/msal-node-samples/testUtils.ts

The "Keep me signed in" page seems to have changed and a selector we were previously waiting for is no longer present. This PR addresses this by changing the selector we wait for.

Fix node tests

---

.github/workflows/beachball-check.yml
.github/workflows/label.yml

Skip beachball and labeler workflows for dependabot PRs as they are expected to fail and not needed. This fixes the username used in the check.

Fix dependabot username in workflow checks

---

samples/msal-angular-v2-samples/angular11-b2c-sample/README.md
samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/app-routing.module.ts
samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/app.component.ts
samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/app.module.ts
samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/failed/failed.component.html
samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/failed/failed.component.spec.ts
samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/failed/failed.component.ts
samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/home/home.component.html
samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/home/home.component.ts
samples/msal-angular-v2-samples/angular11-b2c-sample/test/test.spec.ts

This PR
- expands the sample README in response to issue #3722 and #3730 (possibly).
- adds a `loginFailedRoute` for MsalGuard
- adds subscription to login / token acquisiton failure events

Expand msal-angular B2C sample README

---

change/@azure-msal-common-23d8d974-2351-4a1d-b44a-8dc361d0a0c8.json
lib/msal-common/src/client/OnBehalfOfClient.ts

Modify the on behalf of client access token filter to not include the oboAssertion as part of the cache filter
Fixes the issue #3375

[msal-node]: Modify on-behalf-of client token filter

---

lib/msal-node/docs/initialize-public-client-application.md

Click on the 'PKCE sample' link on [initialize-public-client-application.md](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/initialize-public-client-application.md) page returns a 404 status code. I found the correct link on [README.md](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/README.md) page https://github.com/AzureAD/microsoft-authentication-library-for-js/search?q=auth-code-pkce

Fix broken link in initialize-public-client-application.md

---

extensions/msal-node-extensions/src/persistence/BasePersistence.ts

Doing finally and returning true takes predominance over throwing the error, so the error doesn’t bubble up properly.
verifyPersistence() should return true only if no error was encountered.

[msal-node-extensions] verifyPersistence should not finally return true

---

change/@azure-msal-common-a410d7ad-36b1-4d1c-9c44-b02dfa1012d7.json
lib/msal-common/src/client/SilentFlowClient.ts
lib/msal-common/src/utils/TimeUtils.ts
lib/msal-common/test/client/SilentFlowClient.spec.ts
lib/msal-common/test/utils/TimeUtils.spec.ts

If a user turns back their system clock after a token is acquired they can potentially prolong the amount of time that MSAL will return a cached token to them even though the token may no longer be valid. This PR fixes this behavior by comparing the token `cachedAt` time to the current time and forcing a refresh if the current time is earlier than the cached at time. This is in accordance with the unified cache schema spec.
Fixes #3206

Discard tokens acquired after current time

---

change/@azure-msal-browser-adabc718-b19b-4b98-a5b7-887465c75857.json
lib/msal-browser/src/app/PublicClientApplication.ts
lib/msal-browser/test/app/PublicClientApplication.spec.ts

This adds a `silentRequest` Map to *PublicClientApplication.ts*, and assigns a unique thumbprint to every request made in `acquireTokenSilent`. These thumbprints are used to track requests made, and is designed to gracefully handle multiple concurrent `acquireTokenSilent` calls with the same request. 
This PR addresses #2884.

Msal-Browser supports parallel silent requests

---

change/msal-0d7e07a9-7fe1-468c-8e34-3954a85747cb.json
lib/msal-core/src/UserAgentApplication.ts
lib/msal-core/test/UserAgentApplication.spec.ts

Msal.js v1 uses the global window object to store callbacks and promises, which return the response/error back to the developer. There exists an edge case today that can cause `acquireTokenSilent` to hang and never return anything if another instance of `UserAgentApplication` is instantiated **while** another `acquireTokenSilent` call is in progress. This is due to the fact that the UAA constructor clears the global window objects used to track in progress requests, resulting in the in-progress request losing the reference to the promise it needs to resolve.
This PR addresses this unique scenario by checking if the objects are already defined on the window before instantiating them. It also updates the cleanup logic to delete stale keys rather than just setting the value to `null`.

Fix edge case causing acquireTokenSilent to hang in v1

---

maintenance/passport-azure-ad/package-lock.json
maintenance/passport-azure-ad/package.json

This PR updates the version for the `passport` package from `^0.3.2` to `^0.4.1` inside the `passport-azure-ad` package in order to fix certain bugs.

Update 'passport' from ^0.3.2 to ^0.4.1 for passport-azure-ad

---

change/@azure-msal-angular-2021-08-05-12-45-29-prompt-create-docs.json
change/@azure-msal-browser-2021-08-05-12-45-29-prompt-create-docs.json
change/@azure-msal-react-2021-08-05-12-45-29-prompt-create-docs.json
lib/msal-angular/docs/FAQ.md
lib/msal-browser/FAQ.md
lib/msal-react/FAQ.md

This PR confirms that `prompt=create` passed in the request will trigger the self-service sign-up experience when using msal-angular and msal-react. No further changes needed, docs updated. See #3773 for more details.

Add self-service sign-up entry to msal-angular and msal-react FAQs

---

.github/workflows/msal-angular-e2e.yml
.github/workflows/msal-browser-e2e.yml
.github/workflows/msal-core-e2e.yml
.github/workflows/msal-node-e2e.yml
.github/workflows/msal-react-e2e.yml

Dependabot does not have access to repository secrets and cannot successfully run the E2E tests. This PR skips E2E tests when triggered by dependabot so the PR can be merged. E2E tests can still be run on dependabot PRs by manually re-running the jobs if needed.

Skip E2E tests when triggered by dependabot

---

.github/workflows/msal-angular-e2e.yml

Reverts dependency caching for Angular E2E tests which seems to be causing some memory issues on the Angular9 sample. Will revisit later.

Revert angular e2e caching

---

lerna.json

This isn't needed right now, and just slows down `lerna bootstrap`.

Remove experimental folder from lerna

---

lib/msal-angular/README.md

Removes link from Angular readme to a doc that no longer exists
Addresses #3987

Remove dead link

---

maintenance/passport-azure-ad/.eslintrc
maintenance/passport-azure-ad/lib/aadutils.js
maintenance/passport-azure-ad/lib/bearerstrategy.js
maintenance/passport-azure-ad/lib/constants.js
maintenance/passport-azure-ad/lib/cookieContentHandler.js
maintenance/passport-azure-ad/lib/errors/badrequesterror.js
maintenance/passport-azure-ad/lib/errors/internaloautherror.js
maintenance/passport-azure-ad/lib/errors/internalopeniderror.js
maintenance/passport-azure-ad/lib/index.js
maintenance/passport-azure-ad/lib/jsonWebToken.js
maintenance/passport-azure-ad/lib/jwe.js
maintenance/passport-azure-ad/lib/logging.js
maintenance/passport-azure-ad/lib/metadata.js
maintenance/passport-azure-ad/lib/oidcstrategy.js
maintenance/passport-azure-ad/lib/pem.js
maintenance/passport-azure-ad/lib/sessionContentHandler.js
maintenance/passport-azure-ad/lib/validator.js
maintenance/passport-azure-ad/package-lock.json
maintenance/passport-azure-ad/package.json

**NOTE: This PR replaces #3983, which had failing tests related to upgrading `mocha`.**
This PR adds linting and updates dependencies for the passport-azure-ad library. 
- Upgrades `grunt-contrib-nodeunit`
- Upgrades `https-proxy-agent`, addressing issue #3914 
- Upgrades `lodash` in the package-lock, addressing security advisory [1673](https://www.npmjs.com/advisories/1673)
- Upgrades `path-parse` in the package-lock, addressing security advisory [1773](https://www.npmjs.com/advisories/1773)
- Upgrades `diff` in the package-lock, addressing security advisory [1631](https://www.npmjs.com/advisories/1631)
- Adds `eslint`, `eslint-plugin-header`, `eslint-plugin-security` and lint rules in line with the rest of MSAL.js libraries. Lint errors and warnings addressed. 
- Cleans up comments. …

Address security and linting for passport-azure-ad

---

samples/msal-angular-v2-samples/angular10-sample-app/test/home.spec.ts
samples/msal-angular-v2-samples/angular10-sample-app/test/profile.spec.ts
samples/msal-angular-v2-samples/angular10-sample-app/tsconfig.e2e.json
samples/msal-angular-v2-samples/angular10-sample-app/tsconfig.json
samples/msal-angular-v2-samples/angular11-sample-app/test/detail.spec.ts
samples/msal-angular-v2-samples/angular11-sample-app/test/home.spec.ts
samples/msal-angular-v2-samples/angular11-sample-app/test/lazy.spec.ts
samples/msal-angular-v2-samples/angular11-sample-app/test/profile.spec.ts
samples/msal-angular-v2-samples/angular11-sample-app/tsconfig.json
samples/msal-angular-v2-samples/angular12-sample-app/test/home.spec.ts
samples/msal-angular-v2-samples/angular12-sample-app/test/profile.spec.ts
samples/msal-angular-v2-samples/angular12-sample-app/tsconfig.json
samples/msal-angular-v2-samples/angular9-v2-sample-app/test/home.spec.ts
samples/msal-angular-v2-samples/angular9-v2-sample-app/tsconfig.json
samples/msal-node-samples/auth-code/test/auth-code-aad.spec.ts
samples/msal-node-samples/auth-code/test/auth-code-adfs.spec.ts
samples/msal-node-samples/device-code/test/device-code-aad.spec.ts
samples/msal-node-samples/device-code/test/device-code-adfs.spec.ts
samples/msal-node-samples/silent-flow/test/silent-flow-aad.spec.ts
samples/msal-node-samples/silent-flow/test/silent-flow-adfs.spec.ts
samples/msal-react-samples/gatsby-sample/test/home.spec.ts
samples/msal-react-samples/gatsby-sample/test/profile.spec.ts
samples/msal-react-samples/nextjs-sample/test/home.spec.ts
samples/msal-react-samples/nextjs-sample/test/profile.spec.ts
samples/msal-react-samples/react-router-sample/test/home.spec.ts
samples/msal-react-samples/react-router-sample/test/profile.spec.ts
samples/msal-react-samples/react-router-sample/test/profileRawContext.spec.ts
samples/msal-react-samples/react-router-sample/test/profileWithMsal.spec.ts
samples/msal-react-samples/typescript-sample/test/home.spec.ts
samples/msal-react-samples/typescript-sample/test/profile.spec.ts

Adds a retry to the E2E tests to help alleviate intermittent timeout issues. Each test can be retried individually if a failure occurs

Add retry to E2E tests

---

change/@azure-msal-browser-6b3118fa-4a40-4074-b6e6-b6105beaf751.json
change/@azure-msal-browser-8d31f6e8-6bea-49fa-858f-a2ab0c94b0ec.json
lib/msal-browser/src/cache/BrowserCacheManager.ts
lib/msal-browser/src/interaction_client/BaseInteractionClient.ts
lib/msal-browser/src/interaction_client/StandardInteractionClient.ts

WAM integration will need to use several helper functions that are currently one level deeper than they need to be. This moves the necessary helpers up to `BaseInteractionClient` so they can be used by the forthcoming `WamInteractionClient`

Move helper functions to BaseInteractionClient

---

maintenance/passport-azure-ad/CHANGELOG.md
maintenance/passport-azure-ad/package-lock.json
maintenance/passport-azure-ad/package.json

Bump version to `4.3.1` as `4.3.1-beta.0` has been available for a couple months with no reported issues. Also, moved `eslint` packages to dev dependencies.

Bump passport-azure-ad to 4.3.1

---

.vscode/extensions.json

Adds this extension for better `.env` syntax support: https://marketplace.visualstudio.com/items?itemName=mikestead.dotenv

Add dotenv vscode extension to recommendations

---

.github/workflows/release_automate.yml
release-scripts/getReleaseDate.js

Adds the month of the next release to the title of the release PR that is opened on merges to the dev branch
For example the currently open PR will be renamed to "October 2021 Release"

Dynamically generate release PR title

---

change/@azure-msal-angular-21727384-afef-4632-b791-fc7ccb8406ba.json
change/@azure-msal-browser-66228f71-938f-4236-b100-1efc13a71386.json
change/@azure-msal-node-49a54e51-6f76-4091-a9ee-71918de2f248.json
change/@azure-msal-node-extensions-eec3de90-af9b-4bcc-b3e5-d9af82025a79.json
change/@azure-msal-react-b2f4225a-da79-4b88-a10d-cc0a2c8bdc66.json
change/msal-cbeac37d-4179-45a1-8a3c-668e52a40e08.json
extensions/msal-node-extensions/package.json
lib/msal-angular/package.json
lib/msal-browser/package.json
lib/msal-core/package.json
lib/msal-node/package.json
lib/msal-react/package.json

- Disallows change types other than `prerelease` and `none` for msal-node-extensions, preventing unexpected bumps to `1.0.0`
- Disallows major version bumps in all other packages (with the exception of msal-common)

Fix node extensions beachball bump

---

change/@azure-msal-browser-5d9d1587-039a-4462-8dd3-b48d09664add.json
change/@azure-msal-common-7aa16f1c-8c7e-45db-b518-f5dbb0c48ea3.json
change/@azure-msal-node-c27ce924-c732-41ee-adff-ed3093aafbed.json
lib/msal-browser/src/index.ts
lib/msal-common/src/index.ts
lib/msal-node/src/index.ts

Consistently exports error types thrown by `msal-browser` per #4115.
Resolves #4115

Consistently export error types thrown by msal-browser

---

change/@azure-msal-angular-696d0cf4-bd65-4b35-b426-786857e97f89.json
change/@azure-msal-browser-b1bbc41b-8045-4fe7-8f7c-3e0eff7d177d.json
change/@azure-msal-react-bf95a9c8-65e5-4362-9e2f-7da9ed29069d.json
lib/msal-angular/docs/v2-docs/ssosilent.md
lib/msal-browser/docs/iframe-usage.md
lib/msal-browser/docs/login-user.md
lib/msal-browser/src/error/BrowserAuthError.ts
lib/msal-browser/src/interaction_client/SilentIframeClient.ts
lib/msal-browser/test/error/BrowserAuthError.spec.ts
lib/msal-browser/test/interaction_client/SilentIframeClient.spec.ts
lib/msal-react/docs/hooks.md
samples/msal-browser-samples/VanillaJSTestApp2.0/app/ssoSilentNoHint/auth.js
samples/msal-browser-samples/VanillaJSTestApp2.0/app/ssoSilentNoHint/authConfig.js
samples/msal-browser-samples/VanillaJSTestApp2.0/app/ssoSilentNoHint/graph.js
samples/msal-browser-samples/VanillaJSTestApp2.0/app/ssoSilentNoHint/index.html
samples/msal-browser-samples/VanillaJSTestApp2.0/app/ssoSilentNoHint/ui.js

This PR removes the restriction on the ssoSilent API to require an `account`, `login_hint` or `sid` to initiate a request in a hidden iframe and receive a new authorization code. The API will no longer throw an error, but log a warning that there may not be enough information.

Remove user hint requirement on ssoSilent API
